AcademySoftwareFoundation/openvdb

openvdb/viewer/Camera.cc
openvdb/viewer/Viewer.cc

In systems where the framebuffer and window sizes differ (such as on the OS X Mavericks and later), the framebuffer is the one we want. As it is, the viewport is about a quarter of the window size.

glfw fix: request framebuffer size instead of window's

---

openvdb/CHANGES
openvdb_houdini/houdini/SOP_NodeVDB.cc
openvdb_houdini/houdini/SOP_NodeVDB.h
openvdb_houdini/houdini/SOP_OpenVDB_Advect_Level_Set.cc
openvdb_houdini/houdini/SOP_OpenVDB_Convert.cc
openvdb_houdini/houdini/SOP_OpenVDB_Fill.cc
openvdb_houdini/houdini/SOP_OpenVDB_Filter.cc
openvdb_houdini/houdini/SOP_OpenVDB_Filter_Level_Set.cc
openvdb_houdini/houdini/SOP_OpenVDB_Fracture.cc
openvdb_houdini/houdini/SOP_OpenVDB_Noise.cc
openvdb_houdini/houdini/SOP_OpenVDB_Prune.cc
openvdb_houdini/houdini/SOP_OpenVDB_Resample.cc
openvdb_houdini/houdini/SOP_OpenVDB_Transform.cc

Added SOP_NodeVDB::duplicateSourceStealable() to avoid the cost of a deep-copy when using Houdini's unload flag and updated the following SOPs:
Advect_Level_Set, Convert, Fill, Filter, Filter_Level_Set, Fracture, Noise, Prune, Resample, Transform.

DuplicateSourceStealable

---

openvdb/unittest/TestTree.cc

When building in debug mode, I get an assert firing during a topology union between a leaf and a tile:
```
../openvdb/tree/InternalNode.h:2358: openvdb::v3_1_0::tree::InternalNode<_ChildNodeType, Log2Dim>::TopologyUnion<OtherInternalNode>::TopologyUnion(const OtherInternalNode*, openvdb::v3_1_0::tree::InternalNode<_ChildNodeType, Log2Dim>*) [with OtherInternalNode = openvdb::v3_1_0::tree::InternalNode<openvdb::v3_1_0::tree::InternalNode<openvdb::v3_1_0::tree::LeafNode<float, 3u>, 4u>, 5u>, ChildT = openvdb::v3_1_0::tree::InternalNode<openvdb::v3_1_0::tree::LeafNode<float, 3u>, 4u>, unsigned int Log2Dim = 5u]: Assertion `(t->mValueMask&t->mChildMask).isOff()' failed.
```
This assert isn't present before the recent performance update commit. I have added a reproducing case to the unit …

Add failure case of a union of a leaf and a tile

---

openvdb_houdini/houdini/SOP_OpenVDB_Ray.cc

Distance point attribute created as a float, rather than an int, if it doesn't exist.

Minor change to Ray SOP

---

openvdb/unittest/TestTools.cc
openvdb/unittest/TestTree.cc

On Mac, openvdb::Index64 is uint64_t which is unsigned long long, not unsigned long. This patch fixes the warnings about the mismatching types in the unit tests by using Index64 instead of size_t or 0UL/1UL.

Fix unit test warnings on Mac related to openvdb::Index64

---

openvdb_houdini/houdini/SOP_OpenVDB_Rasterize_Points.cc

findFloatTuple(...) returns a valid handle to the first element of a vector attribute if there is no max_size specified (last argument). Previously vector attributes were being treated as floats.

Fix for rasterizing vector point attributes

---

openvdb/python/pyOpenVDBModule.cc

This fixes the issue faced in issue #68.
There might be a cleaner fix, but this does work.
Tested with Python v2.7, 3.4, and 3.5.

BUG: fix python3/2 numpy import_array macro build issue

---

openvdb/io/Compression.cc

* Set block size as byte size of input buffer which performs better with larger buffers
* Hard-code the type size to be sizeof(float) which performs better with vec3f data

Tuned Blosc parameters for better compression

---

openvdb/tools/MeshToVolume.h
openvdb/tools/VolumeToMesh.h
openvdb_houdini/houdini/GEO_VDBTranslator.cc

Since this is a simple fill of an array, place the minimum grain size as 1024.
This fixes an infinite loop if the number of things to fill falls below the number of threads.

Apply a std::max on grain size to ensure it is never zero.  

---

openvdb/CMakeLists.txt

This fixes the issue where the library the unit tests are built against have OPENVDB_USE_BLOSC enabled, but when the unit tests themselves are built they include headers that don't.

Enable Blosc in CMake C++ Unit Tests

---

openvdb/doc/examplecode.txt

Example code was calling `Tree::signedFloodFill()`, this was replaced by `tools::signedFloodFill()` as of version 3.0.0

Minor update to makeSphereCode in documentation

---

openvdb/points/AttributeSet.cc
openvdb/unittest/TestAttributeSet.cc

This no longer silently allows inserting new attributes with identical names but mis-matching types to an already existing attribute into a Descriptor

Correctly error when inserting a duplicate attribute with mis-matching type

---

openvdb/points/AttributeSet.cc
openvdb/tools/ParticleAtlas.h
openvdb/unittest/TestAttributeArray.cc
openvdb/unittest/TestCoord.cc
openvdb/unittest/TestMultiResGrid.cc
openvdb/unittest/TestPointConversion.cc
openvdb/unittest/TestPointCount.cc
openvdb/unittest/TestPointGroup.cc
openvdb/unittest/TestStreamCompression.cc

- Please recall that on Windows 64-bit, sizeof(long) != sizeof(size_t) 
(https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models)
- Remember: Long is WRONG!
- All input/output files *must* be opened in binary mode

 v3.3.0 Windows fixes

---

openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc

* Change Points Convert SOP default values to not enable normal and color compression by default (this is safer because the range is not guaranteed to be between 0->1)
* Add 16-bit truncate compression as an option to the Points Convert SOP

Adjust Points Convert SOP defaults and add 16-bit truncate compression

---

openvdb_houdini/houdini/SOP_OpenVDB_Points_Group.cc

* Make it so that it works if we're only creating a viewport group
* Avoid assertions in GEO_PrimVDB::makeUniquePtr() that expects no sharing of its grid metadata/transforms

Fix viewport point group behaviour (contributed by Edward Lam)

---

openvdb/points/PointDataGrid.h
openvdb/unittest/TestPointDataLeaf.cc
openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc

When voxel and point attribute data is out-of-core and it is known that all the data will be read from disk, it is faster to sequentially pre-fetch the data using contiguous I/O rather than rely on on-demand loading in a multi-threaded context. Pre-fetching has minimal overhead if the data is already in-core.
Pre-fetching is exposed in the API and used in the Points Convert SOP.

Introduce sequential pre-fetching from disk for faster performance

---

openvdb/unittest/TestPointDataLeaf.cc

AttributeArrays can only use delayed-loading if Blosc is enabled.

Fix PointDataLeaf unit-test when Blosc is disabled

---

openvdb/Makefile
openvdb/points/AttributeSet.cc
openvdb/points/AttributeSet.h
openvdb/points/PointDelete.h
openvdb/unittest/TestAttributeSet.cc
openvdb/unittest/TestPointDelete.cc
openvdb_houdini/Makefile
openvdb_houdini/houdini/PointUtils.cc
openvdb_houdini/houdini/PointUtils.h
openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc
openvdb_houdini/houdini/SOP_OpenVDB_Points_Delete.cc
openvdb_houdini/houdini/SOP_OpenVDB_Points_Group.cc

Add support for deleting points and groups and introduce a new OpenVDB Points Delete SOP. Improvements to OpenVDB Points Convert SOP include no longer deleting non-VDB primitives on conversion, introducing stealable behaviour and auto-population of group field drop-downs.

Point deletion

---

openvdb_houdini/houdini/SOP_OpenVDB_Clip.cc

Minor tweak to the OpenVDB Clip SOP so that the mask input isn't required when frustum clipping in camera mode.

Make OpenVDB Clip SOP mask input optional for camera mode

---

.travis.yml
travis/travis.run

Add these additional options:
* Build and run unit tests using ABI=5 (opt+blosc)
* Build using ABI=5 (opt+no blosc)
* Build using ABI=5 (debug+blosc)
* Build using ABI=5 (debug+no blosc)
Not sure we're ready to deprecate ABI=3 in Travis just yet, but that's probably the next change.

Update Travis to add ABI=5 support

---

openvdb/Makefile

The changes are obvious: remove the hardcoded 'lib' directory name. This allow installation on typical Debian system where 'lib' should be eg. 'lib/x86_64-linux-gnu'

Allow a flexible installation of shared libraries

---

.travis.yml
travis/travis.run

Uses ccache to cache C++ object files and them retrieve them from the cache on subsequent rebuilds for significantly faster Travis builds.

Enable ccache for Travis

---

openvdb/points/AttributeSet.h
openvdb/points/PointDataGrid.h

This will ease the introduction of planned future features by initialising a member variable correctly and adding an extension mechanism to the reading of PointDataLeafNodes for future use.

Add forwards-compatibility reading for ABI=5

---

openvdb/Makefile
openvdb/points/PointCount.h
openvdb/points/PointGroup.h
openvdb/points/PointMask.h
openvdb/unittest/TestPointCount.cc
openvdb/unittest/TestPointMask.cc
openvdb_houdini/houdini/AttributeTransferUtil.h
openvdb_houdini/houdini/PointUtils.cc
openvdb_houdini/houdini/PointUtils.h
openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc

Introduction of mask and point count grid generation in the core API and support as two extra modes in OpenVDB Points Convert SOP. Also includes some refactoring of OpenVDB Points Convert SOP and a few minor conversion bug fixes.

Point Counting and Mask Generation

---

openvdb/Makefile

Makefile build didn't get the Mask.h so it wasn't properly installed in our Make builds.

Add tools/Mask.h to the include list of the Makefile so it is installed

---

openvdb_houdini/houdini/SOP_OpenVDB_Remove_Divergence.cc

The makeGridUnique function on GU_PrimVDB asserts that there is only a single reference on
debug builds.

Avoid having duplicate copies of the grid when invoking makeGridUnique.

---

openvdb_houdini/houdini/SOP_NodeVDB.cc
openvdb_houdini/houdini/SOP_NodeVDB.h
openvdb_houdini/houdini/SOP_OpenVDB_Advect.cc
openvdb_houdini/houdini/SOP_OpenVDB_Advect_Points.cc
openvdb_houdini/houdini/SOP_OpenVDB_Combine.cc
openvdb_houdini/houdini/SOP_OpenVDB_Convert.cc
openvdb_houdini/houdini/SOP_OpenVDB_Create.cc
openvdb_houdini/houdini/SOP_OpenVDB_Filter_Level_Set.cc
openvdb_houdini/houdini/SOP_OpenVDB_From_Particles.cc
openvdb_houdini/houdini/SOP_OpenVDB_From_Polygons.cc
openvdb_houdini/houdini/SOP_OpenVDB_Morph_Level_Set.cc
openvdb_houdini/houdini/SOP_OpenVDB_Noise.cc
openvdb_houdini/houdini/SOP_OpenVDB_Ray.cc
openvdb_houdini/houdini/SOP_OpenVDB_Sample_Points.cc
openvdb_houdini/houdini/SOP_OpenVDB_Scatter.cc
openvdb_houdini/houdini/SOP_OpenVDB_Segment.cc
openvdb_houdini/houdini/SOP_OpenVDB_To_Polygons.cc
openvdb_houdini/houdini/SOP_OpenVDB_To_Spheres.cc
openvdb_houdini/houdini/SOP_OpenVDB_Topology_To_Level_Set.cc

With detached groups, it is not necessary to have a non-const
GU_Detail to create ad-hoc groups, so there is no need to
cast away the const before invoking it.

Create a matchGroup() version that takes a const GU_Detail

---

openvdb_houdini/houdini/PointUtils.cc

Int cannot cast to GA_Offset in our internal strict-type build.

Strict Type fixes.

---

openvdb/math/Math.h
openvdb/math/Tuple.h

MSVC templates this into fpclassify, which is then ambiguous with an int input.  I've worked around it by explicitly casting to (double), but making specializations of openvdb::math::isFinite() may also be an approach.

The standard is unclear if std::isfinite works with int.

---

openvdb_houdini/houdini/GEO_PrimVDB.cc

This ensures axis-aligned transforms don't drift and stop being levelsets.

More aggressive simplification of transforms.

---

openvdb_houdini/houdini/SOP_NodeVDB.cc

This generates an unsafe == warning on MSVC builds.

getUnload() does not return bool so cannot compare with true.

---

travis/travis.run

After adding ccache stats to the final step of the Travis builds, bash was not correctly erroring on the first error, meaning errors typically aren't being reported correctly.

Fix Travis CI error reporting

---

openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc

* Resolve performance issues in partial delete by deleting all VDB primitives from the gdp first
* Add partial delete functionality to mask and count modes
* New toggle enabled for unpack, count and mask modes to selectively retain non-VDB geometry

Improve Points Convert partial delete performance and add a toggle to selectively enable it

---

.travis.yml
travis/travis.run

Extend Travis CI to build the latest production build for Houdini 16.5. This change also handles the fact that Houdini 16.5 no longer ships with Boost.

Add Houdini 16.5 to Travis CI

---

travis/travis.run

Minor fix - remove the hard-coded ABI=3 for Houdini builds in Travis and use the supplied ABI argument. Previously we were always building for ABI=3 (Houdini 15.0, 15.5, 16.0) so this wasn't an issue. Houdini 16.5 is ABI=4.

Fix Travis to use correct ABI version for Houdini

---

openvdb/Types.h
openvdb/math/Mat3.h
openvdb/points/points.cc
openvdb/unittest/TestMath.cc
openvdb/unittest/TestPointAttribute.cc
openvdb_houdini/houdini/AttributeTransferUtil.h
openvdb_houdini/houdini/PointUtils.cc

* Fix a bug where zeroVal<Mat3R>() crashes.
* Add Mat3 as a TypedAttributeArray and support in the Houdini plugin.

Add zeroVal support for Mat3 and Mat3 typed attribute arrays

---

openvdb_houdini/houdini/PointUtils.cc

We ran into an out of bounds write because SizeTraits in the Mat4 case was returning 1.  I couldn't deduce why the template magic was failing, but by rolling the GA_Defaults into the getValues you can avoid a lot of action-at-distance and just make the values array on the stack.  Thus it is more efficient and less error prone.

Fix for building defaults because SizeTraits falsely returns 1 for Mat4.

---

openvdb/points/AttributeGroup.h
openvdb/points/IndexFilter.h
openvdb/points/IndexIterator.h
openvdb/points/PointConversion.h
openvdb/points/PointCount.h
openvdb/points/PointDataGrid.h
openvdb/points/PointMask.h
openvdb/unittest/TestAttributeGroup.cc
openvdb/unittest/TestIndexFilter.cc
openvdb/unittest/TestIndexIterator.cc
openvdb/unittest/TestPointConversion.cc
openvdb/unittest/TestPointCount.cc
openvdb/unittest/TestPointGroup.cc
openvdb/unittest/TestPointMask.cc
openvdb_houdini/houdini/GR_PrimVDBPoints.cc
openvdb_houdini/houdini/PointUtils.cc
openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc
openvdb_houdini/houdini/VRAY_OpenVDB_Points.cc

* Adding extra state() methods to index filter interface to improve optimization opportunities
* Adding active and inactive value mask index filters
* Switching include/exclude groups API to instead use explicit filtering
* Refactoring and simplifying of point count API
* Computing cumulative per-leaf point offsets is now parallelized

Improved Point Filtering and Count Optimizations

---

openvdb/Makefile
openvdb/doc/examplecode.txt
openvdb/points/AttributeArray.h
openvdb/points/PointAdvect.h
openvdb/points/PointCount.h
openvdb/points/PointMask.h
openvdb/points/PointMove.h
openvdb/unittest/TestAttributeArray.cc
openvdb/unittest/TestPointAdvect.cc
openvdb/unittest/TestPointMask.cc
openvdb/unittest/TestPointMove.cc
openvdb_houdini/houdini/SOP_OpenVDB_Advect_Points.cc

Ability to advect VDB Points through a velocity field and a point move API that relies on defining a custom deformer. In addition, some minor changes to AttributeHandle and the addition of methods to IndexFilters that can indicate whether all or none of the points are evaluated. Support for VDB Points advection has been added to OpenVDB Advect Points SOP.

VDB Points Advection

---

cmake/FindGLFW3.cmake

On Ubuntu systems GLFW3 is installed in /usr/lib/x86_64-linux-gnu
so add that as a path suffix so that CMake can pick it up if
available.
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

Add Ubuntu path suffix for GLFW3

---

openvdb/points/PointMask.h
openvdb/points/PointMove.h

A few minor improvements as suggested by @Idclip - improve const-ness of mask methods, switch to vector over std::unordered_map where feasible in index-to-index mappings and coalesce some independent per-leaf functionality
Signed-off-by: Dan Bailey <danrbailey@gmail.com>

Minor point move improvements

---

.travis.yml
openvdb/CHANGES
openvdb/INSTALL
openvdb/doxygen-config
openvdb/points/AttributeArray.cc
openvdb/points/AttributeArray.h
openvdb/points/AttributeGroup.cc
openvdb/points/PointAttribute.h
openvdb/points/PointDelete.h
openvdb/points/StreamCompression.cc
openvdb/points/StreamCompression.h
openvdb/unittest/TestAttributeArray.cc
openvdb/unittest/TestAttributeArrayString.cc
openvdb/unittest/TestAttributeGroup.cc
openvdb/unittest/TestAttributeSet.cc
openvdb/unittest/TestPointAttribute.cc
openvdb/version.h
openvdb_houdini/houdini/ParmFactory.cc
openvdb_houdini/houdini/ParmFactory.h
openvdb_houdini/houdini/PointUtils.cc
openvdb_houdini/houdini/PointUtils.h
openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc

* Added ABI=6, bumped Travis to build for ABI=6 and deprecated some older ABI builds
* Add various new methods to AttributeArray for querying value and storage type and size metadata
* In-memory compression for AttributeArray has now been deprecated
* AttributeArray member variables have been unioned, cleaned up and packed to reduce memory from 64 bytes to 40 bytes (for an empty array)
* New AttributeArray copyValues() method that can copy batches of attributes using a custom iterator to avoid the cost of doing a virtual function call per-point
* Add copyValues() implementation to deletion of points to accelerate this method for ABI=6
* Add extra AttributeArray read checks to error if attempting to access or write partially-read arrays

ABI=6 and Fast AttributeArray Copying

---

openvdb_houdini/houdini/SOP_OpenVDB_From_Particles.cc

Fixed an issue which would stop attribute transfers if no primary output was selected

Fixed a backwards compatibility bug with SOP_OpenVDB_From_Particles

---

.travis.yml
README.md
travis/travis.run

* Updated our Travis CI build to use Ubuntu 16.04 (Xenial) from 14.04 (Trusty)
* Added support for building Houdini 17.0 DSOs (relatively easy when using Xenial)
* Various other minor changes to resolve issues in bumping major version of Ubuntu
* Increased CI to also now build python bindings, VDB binaries, C++ and Python documentation
* Add a Travis CI badge to GitHub repo landing page to highlight pass/fail state of master branch

Travis CI Update and H17 Support

---

openvdb/points/AttributeArrayString.cc
openvdb/points/AttributeArrayString.h
openvdb/unittest/TestAttributeArrayString.cc

Added missing array() method for StringAttributeHandle and StringAttributeWriteHandle. Also added convenience hasIndex() method to StringAttributeWriteHandle for checking if a string exists in the metadata cache already.
Updated StringAttributeWriteHandle unit tests to use hasIndex to verify it is working as intended.

Add methods to StringAttributeArray and StringAttributeWriteHandle

---

openvdb/points/AttributeArray.h
openvdb/unittest/TestAttributeArray.cc

Creating two AttributeArrays of a type that has yet to be initialized and attempting to compare them would cause a seg-fault as the equality method was previously comparing uninitialized static memory that was only lazy-initialized by calling attributeType().

Fix seg-fault when attempting to compare AttributeArrays of an unregistered type

---

openvdb/python/pyOpenVDBModule.cc

Clang reports "`warning: equality comparison with extraneous parentheses
[-Wparentheses-equality]`" when expanding the `PyBool_Check` macro in the
context of a conditional expression.

Minor fix to address Clang parenthesization warning

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/doxygen-config
openvdb/version.h

Downgraded library version to 6.0.1 from 6.1.0 pending any API-breaking changes and removed a broken Doxygen link.
Reviewers: @kmuseth  @danrbailey

Downgrade library version to 6.0.1

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/tools/Clip.h

[OVDB-1](https://jira.aswf.io/browse/OVDB-1)
Except when clipping against a camera frustum, the Clip tool didn't properly
copy metadata from the input grid to the output grid.

OVDB-1: Fixed metadata handling in the Clip tool.

---

openvdb/Platform.h
openvdb/points/PointMove.h
openvdb/unittest/TestAttributeArray.cc
openvdb/unittest/TestAttributeSet.cc
openvdb/unittest/TestPointAttribute.cc
openvdb/version.h

These macros disable deprecation warnings from Clang, GCC and ICC.
With GCC and ICC, the macros also output a `#pragma message`, so as to discourage their use long-term.  (With Clang, there doesn't appear to be a way to output a message without generating a warning.)
Reviewers: @kmuseth @danrbailey

Add OPENVDB_NO_DEPRECATION_WARNING_BEGIN/END macros

---

openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc

When merging into H17, I found the building of the group from gdp rather than inputGeo(1) causes problems when not in keep input mode.   I also changed the default to not keep the input as I believe that matched the old tools (But it could be an old default on our part?)

Use the inputGeo() for the group generation and default Keep Input Off

---

.travis.yml
travis/travis.run

* Split out header tests into a separate concurrent job
* Removing the building of Python module and binaries from Houdini builds
Results in ~44m being the longest build when caching is not being used.

OVDB-13: Optimize Travis build

---

openvdb_houdini/houdini/SOP_OpenVDB_Rasterize_Points.cc

Direct access to .timeDep has been deprecated for a long time, but
will actually be gone in 17.5; so replace with the long-standing
setTimeDep.

Replace direct .timeDep with setTimeDep, required in 17.5.

---

openvdb/doc/changes.txt
openvdb/math/DDA.h
openvdb/math/Mat.h
openvdb/python/pyAccessor.h
openvdb/python/pyGrid.h
openvdb/python/pyutil.h
openvdb/tools/Composite.h
openvdb/tools/DenseSparseTools.h
openvdb/tools/Filter.h
openvdb/tools/LevelSetFracture.h
openvdb/tools/LevelSetMorph.h
openvdb/tools/LevelSetTracker.h
openvdb/tools/Morphology.h
openvdb/tools/ParticleAtlas.h
openvdb/tools/ParticlesToLevelSet.h
openvdb/tools/PointsToMask.h
openvdb/tools/RayTracer.h
openvdb/tools/Statistics.h
openvdb/tools/TopologyToLevelSet.h
openvdb/tools/ValueTransformer.h
openvdb/tools/VolumeAdvect.h
openvdb/tree/LeafManager.h
openvdb/unittest/TestPointConversion.cc
openvdb/util/NodeMasks.h
openvdb/util/NullInterrupter.h
openvdb/viewer/RenderModules.cc
openvdb_houdini/houdini/PointUtils.h

[OVDB-10](https://jira.aswf.io/browse/OVDB-10): Introduce stricter Clang and GCC warnings for Travis builds
More work to be done, but this should significantly reduce the volume of warnings from GCC 5.4 and Clang 7.
For the Python module and unit test warnings, we'll need to look into why Clang is seemingly not respecting `-isystem`.

OVDB-10: Fixes for various GCC 5.4 and Clang 7 warnings

---

openvdb/io/io.h
openvdb/unittest/TestAttributeArray.cc

This new friend class is used to expose the constructor of io::MappedFile for use in the unit tests for AttributeArray, which makes them simpler.

Refactor TestAttributeArray and add a new friend class to io::MappedFile

---

CMakeLists.txt
openvdb/Makefile
openvdb_houdini/Makefile
openvdb_maya/Makefile
travis/travis.run

- Introduced a set of pre-defined compiler warnings for gcc and clang for all projects. 
- Updated travis to use warnings flag

Pre-defined compiler warnings for gcc and clang

---

.cirrus.yml

Adds a Cirrus CI validation check for Doxygen. This builds and validates the Doxygen for the core library in under a minute from the PR being submitted.
(Note that I ran into a bug in this version of Doxygen when using a newline character in a default value so this check is currently ignored for util/Formats.h)

Doxygen Validation

---

openvdb/unittest/TestTypes.cc

GCC 4.8 reported "`openvdb/unittest/TestTypes.cc:54:1: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without TestTypes::testTraits()`".

Split up TestTypes::testTraits to avoid variable tracking size limit

---

openvdb/cmd/openvdb_lod/main.cc

Minor warning fix to openvdb_lod/main.cc when building without log4cplus:
```cmd/openvdb_lod/main.cc:172:18: warning: unused variable ‘msec’ [-Wunused-variable]```

Minor warning fix to LOD binary

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/points/AttributeArrayString.cc
openvdb/points/AttributeArrayString.h
openvdb/unittest/TestAttributeArrayString.cc

Main contributions are the significant improvements to the construction and cache of the StringMetaInserter. This currently only manifests during point conversion as there isn't really anything else that deals with string attributes. However these improvements drastically speed up algorithms in AX and Point Merging (which I'll push up for discussion afterwards). 
Performance statistics here:
https://pastebin.com/TN9jwRQT
I've not included memory statistics but hopefully it's pretty apparent without me needing to provide exact numbers
Note that this does change ABI for the StringMetaInserter:

Point String Attribute Improvements

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/tools/MeshToVolume.h

Check for NANs when computing distances to avoid infinite loops
with bad input geometry.
Rename the computeDistance to updateDistance to better reflect
its behaviour.

OVDB-27: MeshToVolume uses infinite memory when given NANs

---

openvdb/CHANGES
openvdb/Metadata.h
openvdb/Types.h
openvdb/doc/changes.txt
openvdb/openvdb.cc
openvdb/python/pyOpenVDBModule.cc
openvdb/python/test/TestOpenVDB.py
openvdb/unittest/TestMetadata.cc
openvdb/unittest/TestMetadataIO.cc

- Added `Vec4i`, `Vec4s` and `Vec4d` metadata types.
- Added `typeNameAsString` specializations for Vec4 types.
- Added Vec4 metadata support to pyopenvdb.
- Refactored metadata unit tests and added Vec4 tests.

OVDB-40: Add support for Vec4 metadata

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb_houdini/houdini/SOP_OpenVDB_Vector_Merge.cc

VDB Vector Merge will better preserve metadata if it uses buildFromGrid.
Bug: 95536

VDB Vector Merge preserves Metadata

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/points/AttributeArray.h
openvdb/tree/LeafBuffer.h
openvdb/unittest/TestPointMove.cc
openvdb/util/PagedArray.h

With the combination of GCC 6.3 and TBB 4.4.6 (not one of the VFX platform configurations), I'm getting errors like this:
```
openvdb/tree/LeafBuffer.h:254:19: error: no matching function for call to ‘tbb::atomic<unsigned int>::atomic(int)’
, mOutOfCore(0)
^
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note: candidate: tbb::atomic<unsigned int>::atomic()
__TBB_DECL_ATOMIC(unsigned)
^
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note:   candidate expects 0 arguments, 1 provided
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note: candidate: constexpr tbb::atomic<unsigned int>::atomic(const tbb::atomic<unsigned int>&)
tbb/4.4.6.0/include/tbb/atomic.h:468:1: note:   no known conversion for argument 1 from ‘int’ to ‘const tbb::atomic<unsigned int>&’
In file included from openvdb/points/AttributeGroup.h:40:0, …
```

Fixes for tbb::atomic errors reported by GCC 6.3

---

.travis.yml
openvdb/Grid.h
openvdb/Types.h
openvdb/version.h

I looked at adding deprecations around all functions and classes, but it didn't seem all that useful. Most of the ABI macro branching is to add new functions which is obviously not going to trigger deprecated warnings. In addition, many of the ABI changes are subtly changing the existing function signature (adding a const for example). I think this might not be a particularly obvious way of alerting the user.
Instead I've gone with the following, simply making a compile error with a clear error message. A compiler flag can then optionally suppress the error. I considered using #warning or pragma warnings to achieve the same thing, but this is not very portable, so this approach seemed less problematic.
Looking for some input on the mechanism that the user could use to provide the …

OVDB-68: Add an error directive if using a deprecated version of the OpenVDB ABI

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/points/PointMove.h
openvdb/unittest/TestPointMove.cc

Resolve issues with filtered point re-bucketing by removing the optimization that attempts to use a padded vector instead of a hash map within a certain threshold. There are other potential avenues of optimization that are worth exploring here.

OVDB-58: Fix bug with filtered point re-bucketing

---

openvdb/Grid.h
openvdb/Platform.h
openvdb/math/Operators.h
openvdb/math/Stencils.h
openvdb/math/Vec3.h
openvdb/tools/Filter.h
openvdb/tools/GridTransformer.h
openvdb/tools/Interpolation.h
openvdb/tools/MultiResGrid.h
openvdb/unittest/TestLevelSetUtil.cc
openvdb/unittest/util.h
openvdb_houdini/houdini/SOP_OpenVDB_Combine.cc
openvdb_houdini/houdini/SOP_OpenVDB_Prune.cc

These changes either fix or suppress all warnings on GCC 6.3.0 for the core library, binaries, python module and Houdini SOPs. I've tested on Linux through Circle CI using CMake, which is the first target for enabling this. The changes to enable this in Circle/CMake will be forthcoming once #382 is merged.
This PR represents a kind of amnesty - all existing conversion issues (and there are quite a lot of them!) are simply suppressed using pragmas so that we can switch on warnings as errors. The aim being to ensure that any tools or changes introduced going forward are required to meet the new higher standard. In time, we can discuss the best way to go about resolving the existing issues and removing the pragmas. Where possible, I've refactored slightly to introduce pragmas around the …

OVDB-15: Fix/Suppress Warnings

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/points/AttributeSet.cc
openvdb/unittest/TestAttributeSet.cc

Fix a bug where the stride of existing attribute arrays was being ignored during copy construction of AttributeSets. This was reported as a result of attempting to use point deletion through the VDB Points Delete SOP in which an error was displayed on the SOP.
The itself fix is trivial, so I'd like to include it in the upcoming release if possible.

Fix Stride for AttributeSet Copy-Constructor

---

.circleci/config.yml

There are a number of memory allocation bug fixes in between TBB 4.4.0 and 4.4.6, so bumping to a later version of TBB 4.4 in the hope of improving stability in the ABI=4 build on Circle. I've yet to see a 4.4.6 build fail.
(This is a CI change so not required for the release).

Bumping TBB version from 4.4.0 to 4.4.6 for ABI=4 CI build

---

openvdb/python/CMakeLists.txt
openvdb/python/pyOpenVDBModule.cc

Fixes for Python3 and loading the python module on MacOS

---

openvdb/INSTALL

There's a good argument to remove this file entirely, but for the time being, just update the versions and add a link to point to the CMake build documentation.

OVDB-71: Update INSTALL file minimum versions and add link to build documentation

---

CMakeLists.txt
openvdb/CHANGES
openvdb/doc/changes.txt

This fixes the case where users have wrapped our CMakeLists.txt with their own via things like `include()`, which results in a different value for CMAKE_SOURCE_DIR

CMake root path improvements

---

openvdb/CHANGES
openvdb/Grid.h
openvdb/doc/changes.txt
openvdb/unittest/TestGrid.cc
openvdb_houdini/GEO_PrimVDB.h
openvdb_houdini/SOP_OpenVDB_Fill.cc
openvdb_houdini/Utils.h

I would actually prefer `GEOvdbApply` to be a member of the primitive (i.e., `GEO_PrimVDB::apply`), but then for older Houdini versions we'd still need a free function.

OVDB-94: makeGridUnique fix for Fill SOP

---

.circleci/config.yml
CMakeLists.txt
appveyor.yml
ci/install.sh
ci/install_jemalloc.sh
cmake/FindJemalloc.cmake
cmake/FindTBB.cmake
cmake/OpenVDBHoudiniSetup.cmake
openvdb/CHANGES
openvdb/CMakeLists.txt
openvdb/doc/changes.txt

Add support for Jemalloc and TBB malloc and enable Jemalloc by default.
This seems to build for me on Linux and Windows fine. @jmlait - a quote from your chapter in "Multithreading for Visual Effects":
> On platforms where linking to jemalloc is not practical, we resort to tbb::malloc_proxy.
Can you expand on this? Are there any platforms that you'd suggest we make TBB malloc the default? Also curious to know if there is any configuration in which Houdini is shipped _without_ using Jemalloc?

OVDB-96: CMake Memory Allocators

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb_houdini/ParmFactory.cc
openvdb_houdini/ParmFactory.h
openvdb_houdini/SOP_NodeVDB.cc
openvdb_houdini/SOP_NodeVDB.h
openvdb_houdini/SOP_OpenVDB_Advect.cc
openvdb_houdini/SOP_OpenVDB_Convert.cc
openvdb_houdini/SOP_OpenVDB_Densify.cc
openvdb_houdini/SOP_OpenVDB_Fill.cc
openvdb_houdini/SOP_OpenVDB_Filter.cc
openvdb_houdini/SOP_OpenVDB_Metadata.cc
openvdb_houdini/SOP_OpenVDB_Noise.cc
openvdb_houdini/SOP_OpenVDB_Platonic.cc
openvdb_houdini/SOP_OpenVDB_Points_Convert.cc
openvdb_houdini/SOP_OpenVDB_Points_Delete.cc
openvdb_houdini/SOP_OpenVDB_Potential_Flow.cc
openvdb_houdini/SOP_OpenVDB_Prune.cc
openvdb_houdini/SOP_OpenVDB_Rasterize_Points.cc
openvdb_houdini/SOP_OpenVDB_Read.cc
openvdb_houdini/SOP_OpenVDB_Rebuild_Level_Set.cc
openvdb_houdini/SOP_OpenVDB_Remap.cc
openvdb_houdini/SOP_OpenVDB_Sample_Points.cc
openvdb_houdini/SOP_OpenVDB_Scatter.cc
openvdb_houdini/SOP_OpenVDB_Sort_Points.cc
openvdb_houdini/SOP_OpenVDB_To_Polygons.cc
openvdb_houdini/SOP_OpenVDB_Transform.cc
openvdb_houdini/SOP_OpenVDB_Write.cc

This adds the ability to hide an open-source SOP from the tab menu using OpFactory::setInvisible(). It also adds the ability to "pair" an open-source SOP with a native SOP shipped by SideFX. This is achieved through a getParentName() rule in the OpPolicy classes and by using OpenVDBOpFactory::setParentName("...") for cases where it deviates from this logic (currently Advect and Filter SOP).
I have included setParentName("") with an empty string for cases where the open-source SOP **isn't** shipped with Houdini (OpenVDB Densify SOP for example). If the sole use-case is for ophiding, this isn't strictly necessary because it shouldn't matter if the native SOP doesn't exist, but I included it anyway so the pairing is accurate. 
No SOPs are being marked invisible with this PR, so this is just …

OVDB-64: Add SOP Pairing Logic

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb/points/IndexFilter.h
openvdb/points/PointMove.h

This is a simple performance improvement to switch a couple of std::maps to std::unordered_maps as an openvdb::Coord hash is now available.

Use hash map with Coord key for faster performance

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb_houdini/ParmFactory.cc
openvdb_houdini/ParmFactory.h
openvdb_houdini/SOP_NodeVDB.cc

Add a tab sub-menu option to OpPolicy/OpFactory and set OpenVDB SOPs to use "ASWF" instead of "Custom".

OpenVDB SOPs Tab Sub-Menu

---

openvdb/CHANGES
openvdb/doc/changes.txt
openvdb_houdini/ParmFactory.cc
openvdb_houdini/ParmFactory.h
openvdb_houdini/SOP_NodeVDB.cc
openvdb_houdini/SOP_NodeVDB.h

This PR adds a spare data mechanism to `OP_Operator`s created with `OpFactory`.  I deliberately kept the API simple (we can extend it if the need arises, but multi-gigabyte spare data is already supported), and I have not included any ophide logic (I will file my `pythonrc.py` implementation as a separate PR).
To complement the C++ API, I've added HScript and Python functions to retrieve (but not set) spare data:
**HScript**
```
> opsparedata
opsparedata
List spare data associated with an operator type.
USAGE
opsparedata <networktype> <opname> [<token>]
When the token is omitted, all (token, value) pairs
associated with the operator type are displayed.
Currently, only operator types defined with OpenVDB's OpFactory
can have spare data.  See www.openvdb.org for more information.
EXAMPLES
> …
```

OVDB-106: Add spare data support to OpenVDB operators

---

cmake/OpenVDBHoudiniSetup.cmake

Fix to a new linking error on Mac OSX that's just started happening:
```
Undefined symbols for architecture x86_64:
"hboost::this_thread::interruption_point()", referenced from:
hboost::condition_variable::wait(hboost::unique_lock<hboost::mutex>&) in ParmFactory.cc.o
hboost::condition_variable::do_wait_until(hboost::unique_lock<hboost::mutex>&, timespec const&) in ParmFactory.cc.o
"hboost::detail::get_current_thread_data()", referenced from:
hboost::detail::interruption_checker::interruption_checker(_opaque_pthread_mutex_t*, _opaque_pthread_cond_t*) in ParmFactory.cc.o
ld: symbol(s) not found for architecture x86_64
```
On investigation, it seems that it's coming from introducing HOM_AutoLock in #463 which itself uses UT_TaskLockT which uses boost::thread.

Add hboost thread as dependency to resolve linking error

---

CHANGES
CMakeLists.txt
doc/changes.txt

Not sure how much collective time has been spent over the years wrangling colored output from compilers. Many google hits still seem to reference a perl script to color the output.
One simple solution is to define GCC_COLORS in the environment which will be recognized by GCC >= 4.9. This is a convenient alternative that simply sets -fdiagnostics-color=always in GCC or -fcolor-diagnostics in Clang. Perhaps when we deprecate support for GCC 4.8 we could even enable this by default.

Add option to use colored output through CMake

---

CHANGES
doc/changes.txt
openvdb/tools/FindActiveValues.h
openvdb/unittest/CMakeLists.txt
openvdb/unittest/TestFindActiveValues.cc

Finds the active values in a tree which intersects a bounding box.
Two methods are provided, one that counts the number of active values
and one that simply tests if any active values intersect the bbox.

Added FindActiveValues

---

openvdb_houdini/GEO_PrimVDB.cc
openvdb_houdini/GEO_PrimVDB.h
openvdb_houdini/GEO_VDBTranslator.cc
openvdb_houdini/GT_GEOPrimCollectVDB.cc
openvdb_houdini/GT_GEOPrimCollectVDB.h
openvdb_houdini/GU_PrimVDB.cc
openvdb_houdini/GU_PrimVDB.h
openvdb_houdini/SOP_VDBVerbUtils.h
openvdb_houdini/UT_VDBUtils.cc
openvdb_houdini/UT_VDBUtils.h

Replace the PROPRIETARY notices with copyright notices to make
the intention clear.  This should make it clear that the wrapped
Dreamworks license applies to the content.

Replace the PROPRIETARY notices with copyright notices to make

---

openvdb_houdini/SOP_OpenVDB_Filter.cc

The OpenVDB Filter SOP label was renamed to VDB Smooth SOP, but the underlying operator type name wasn't set back to the original name as it should have been. This corrects that error and adds an alias just in case anyone has picked this up in the interim.

Add missing internal name for VDB Filter SOP and alias

---

openvdb/tools/FindActiveValues.h

This is so that you can #include "tools/FindActiveValues.h" in an empty cpp without needing additional header includes.

Add missing tbb includes to FindActiveValues

---

openvdb/points/AttributeArray.h

I do not like this change overmuch, but it was required for our builds to avoid deprecation failures.  When the compress() method is instantiated in the derived templated class, MSVC will generate deprecation failures since the pure virtual base method is deprecated.  This is clearly wrong as the overridden version has also been marked deprecated.
We have not found a good solution internally to deal with this with our deprecations.  Usually we are forced to just disable deprecations on the entire derived class.
I've also added a missing deprecation on the derived set() method.

Marking base virtual functions deprecated is painful in Windows, so removing it.

---

tsc/process/deprecation.md

Improve wording of the deprecation strategy to try and eliminate confusion when we support the next year of the VFX Reference Platform before the end of the calendar year, as discussed in:
https://github.com/AcademySoftwareFoundation/openvdb/blame/master/tsc/meetings/2019-08-29.md#L85
Also include a clause that extends support of the previous ABI until the subsequent minor release to allow a little extra migration time.

Update OpenVDB Deprecation Strategy

---

CHANGES
doc/changes.txt
openvdb_houdini/ParmFactory.cc
openvdb_houdini/SOP_NodeVDB.cc

By introducing this override we need to be able to distinguish between the Houdini default (such as "17.5.204") and the VDB version (such as "6.2.0") in a syncNodeVersion() override.
I considered adding a prefix (such as "vdb:6.2.0") then settled on using the packed integer representation (such as "100794368"). Simply checking the string is non-empty and contains no "." characters is thus sufficient to determine this is a VDB version and not a Houdini version. I also couldn't think of any reason to need to preserve which version of Houdini this node was created in, in addition to which version of VDB was used. Native Houdini VDB nodes will still use the Houdini version.
Of course if there's any logic expecting the Houdini default form (X.Y.Z.W) then this will break, but I'm not aware of …

OVDB-53: Provide OP_Operator::getVersion override to return VDB version

---

azure-pipelines.yml
openvdb/python/CMakeLists.txt
openvdb/unittest/CMakeLists.txt

Using ctest ensures that the python tests are also run

Run verbose tests and use ctest in CI

---

openvdb/Platform.h

Attempt to get proper deprecation pragmas on Windows.

Add the correct pragmas to disable deprecation warnings on MSVC.

---

openvdb_houdini/SOP_OpenVDB_LOD.cc

Explicitly write out the name attribute into the grids before
processing, as they will internally use the name metadata to generate
the output names.  Otherwise our names will go out of sync and
not respect up-stream Name SOPs.
Bug: 96367

Explicitly write out the name attribute into the grids

---

openvdb_houdini/SOP_OpenVDB_Resample.cc

Rename the Translate parameter and update the help to reflect that it is stuck in index space.
Bug: 87783

Rename the Translate parameter and update the help to reflect truth.

---

openvdb/unittest/TestFile.cc
openvdb/unittest/TestStreamCompression.cc

blosc >= 1.15 requires `const char**`, older versions require `char**`.

openvdb/unittest: blosc 1.15 compatibility

---

CHANGES
doc/changes.txt
openvdb/cmd/openvdb_render.cc

Paraphrasing from an OpenEXR change log:
> If you are using any OpenEXR DLLs on Windows, you must define OPENEXR_DLL in your project's preprocessor directives.
My understanding is that we're handling this with the following logic in openvdb/PlatformConfig.h:
```
// By default, assume that we're dynamically linking OpenEXR, unless
// OPENVDB_OPENEXR_STATICLIB is defined.
#if !defined(OPENVDB_OPENEXR_STATICLIB) && !defined(OPENEXR_DLL)
#define OPENEXR_DLL
#endif
```
However in the vdb_render binary, the OpenEXR headers are included before this PlatformConfig header so this OPENEXR_DLL is not defined early enough which causes an undefined symbol issue as described in detail here (https://github.com/AcademySoftwareFoundation/openvdb/issues/496).
I believe a pending change in OpenEXR 2.4 will …

Fix OpenEXR VDB Render issue on Windows

---

openvdb_houdini/GEO_PrimVDB.cc
openvdb_houdini/GEO_PrimVDB.h

Duplicate the makeGridUnique as isGridUnique that allows testing if grids are shared before necessarily uniquing them.
This is a non-compiling reference change to track the internal GEO_PrimVDB version of Houdini 18.

Add isGridUnique.

---

openvdb/Grid.cc
openvdb/Metadata.cc
openvdb/math/Maps.cc
openvdb/math/Maps.h
openvdb/points/AttributeArray.h
openvdb/tree/Tree.h

Hi,
over at Autodesk we run OpenVDB under Valgrind, and we discovered that OpenVDB leaks a number of singletons in static variable pointers. This patch fixes these memory leaks.
Notice, we have used Meyers singleton pattern makes sure that the singletons are only allocated once the static function they reside in is called. This is also thread-safe in C++11 and above.
In AttributeArray,h it was not as straight-forward to use this pattern since the singleton's constructor depending on some code outside the class. In that case (and in Tree.h) we instead used std::call_once which is also thread-safe and serves the same purpose.

Fix memory leaks in static variable pointers.

---

CHANGES
doc/changes.txt
openvdb_houdini/SOP_OpenVDB_Rasterize_Points.cc

When transferring attributes, the Rasterize Points SOP computes density-weighted sums over neighboring points, and if there are clusters of points with extremely small (subnormal) densities, normalization by the sum of those densities can produce NaNs or infs.  This PR adds logic to check for and suppress non-finite values.
This also serves as a DWA test of EasyCLA.

Rasterize Points SOP non-finite value fix

---

README.md
doc/faq.txt

In connection with #560 and #565, this PR removes a couple
of statements that referred to the extra contents of the old
LICENSE file. It also updates the Mozilla Public License URL
to an https version.
Signed-off-by: Steve Winslow <swinslow@gmail.com>

Update references to project license

---

CHANGES
CMakeLists.txt
doc/build.txt
doc/changes.txt

As discussed here:
https://github.com/AcademySoftwareFoundation/openvdb/blame/master/tsc/meetings/2019-10-10.md#L46
Disable the Python Module in CMake by default so that it's more likely that a first time user attempting to build OpenVDB will succeed.

Python Module Option Now Off in CMake

---

.github/workflows/build.yml
CHANGES
azure-pipelines.yml
doc/changes.txt
openvdb/Platform.h
openvdb/util/NodeMasks.h

This is an implementation derived from #493 to be included in the 7.0 release. Differences between that PR include:
* OPENVDB_SSE42 flag used to opt-in to using hardware intrinsics
* Intrinsic headers included in Platform.h
* Hardware intrinsics only used for the two most common methods (CountOn() and FindLowestOn() with Byte and Index64 variants)
* 32-bit Windows uses software implementation for CountOn(Index64)
* Implementation introduced directly into NodeMasks.h using conditional macros instead of additional header files
* CI extended to evaluate the unit tests on SSE 4.2 builds of OpenVDB
@Const-me - I'd much appreciate you reviewing this change. Also, we typically use the contributors full name in the release notes, but I only have your first name - so let me know if you'd like me …

Add SIMD Instructions to NodeMask

---

CHANGES
doc/changes.txt
openvdb/points/AttributeArray.cc
openvdb/points/AttributeArray.h

This is an ABI=7 change to make the AttributeArray copy constructor thread-safe.
I also made a few minor improvements, deprecating the bool argument in the copy constructor and marking the copyUncompressed() method as deprecated.
I recommend looking at this PR commit-by-commit as it should be easier to see what's changing.

OVDB-33: AttributeArray Thread-Safety

---

.github/workflows/build.yml
azure-pipelines.yml
ci/build_houdini.sh
ci/install_houdini.sh

@jmlait - I just tried adding H18 to the CI and aside from having to install the future and lxml python modules, am now getting this error:
> CMake Error at hou/toolkit/cmake/HoudiniConfig.cmake:130 (message):
>   Error running /__w/openvdb/openvdb/hou/bin/hython: No licenses could be
>   found to run this application.
> 
>   	Please check for a valid license server host
Any ideas what might be going on? This works for H17 and H17.5, I'm not aware there's been any license server changes. :/

Add Houdini 18.0 to CI

---

CHANGES
doc/changes.txt
openvdb/tree/Tree.h
openvdb/unittest/TestGridBbox.cc

The interface for evalActiveVoxelBoundingBox suggests it returns false.
if empty, but only does so if the tree is empty.  This will change
it so it will also do so if the computed bounds are empty.

The interface for evalActiveVoxelBoundingBox suggests it returns false.

---

openvdb_houdini/GEO_PrimVDB.h
openvdb_houdini/UT_VDBUtils.h

This is a reference commit to keep the Houdini & VDB versions in sync.
Primary change is a sprinkling of force inline.  To ensure abi compatibility it is important these functions are always inlined so as to use the caller's version of the VDB grid.

Add inlines and fix MSVC clang paths.

---

openvdb_houdini/GEO_PrimVDB.h
openvdb_houdini/UT_VDBUtils.h

With the current min-spec for MSVC, we do not need special case code.

With the current min-spec for MSVC, we do not need special case code.

---

openvdb/tools/MeshToVolume.h

MeshToVolume uses axis-aligned rayfires to detect voxels that
are clearly "outside" the volume.  (Connected to infinity by voxels
with dist > 0.75). This does not detect all such voxels, as there may be
voxels that are "in shadow". It therefore then propagates the "outside"
state to adjacent voxels with dist >0.75.
For reasons of performance, the existing algorithm separates
propagation within a node (contiguous memory) and between nodes.
It also uses a mask to avoid performing unnecessary work where
nothing has changed. I believe the logic around the mask is
overaggressive, and leads to some edge cases where necessary
propagation doesn't occur across node boundaries. This leads to
voxels incorrectly being marked "inside", which can result in very
visible shape changes in the result.
- …

Fix sign propagation bug in MeshToVolume

---

CHANGES
doc/changes.txt
openvdb/points/AttributeArray.h

Rounding from float -> int can be achieved with a simple cast *provided* that the floating-point value is always positive. As we're independently handling the case where the value is not positive, we can remove the redundant floor operation. This improved performance of this method by ~10% in my testing.
This method is used a lot so I tested all possible 32-bit floating-point values to be sure I wasn't missing something.

Fixed Point Optimization

---

CHANGES
CMakeLists.txt
doc/changes.txt

As discussed, add a CMake check to ensure that at least the minimum supported version of MSVC is being used.
(@e4lam)

Add minimum MSVC version to CMake

---

CHANGES
cmake/FindIlmBase.cmake
cmake/FindOpenEXR.cmake
doc/changes.txt

As far as I can tell this fixes the problem reported in the following issues:
https://github.com/AcademySoftwareFoundation/openvdb/issues/632
https://github.com/AcademySoftwareFoundation/openvdb/issues/144
and can be reproduced with the following CMake (un-comment `get_filename_component` for the fix)
```cmake
cmake_minimum_required(VERSION 3.1)
project(TEST LANGUAGES CXX)
add_executable(tmp main.cpp)
set(IPATH /usr/include/../include)
#get_filename_component(IPATH ${IPATH} ABSOLUTE)  
target_include_directories(tmp SYSTEM PUBLIC ${IPATH})
```

Bugfix for relative -isystem paths changing search order

---

CHANGES
doc/changes.txt
openvdb/points/AttributeSet.cc
openvdb/points/AttributeSet.h
openvdb/points/PointDataGrid.h
openvdb/unittest/TestAttributeSet.cc
openvdb/unittest/TestPointDataLeaf.cc

Two new additions related to stealing data from a Point Data Grid:
* PointDataLeafNode::stealAttributeSet() - releases ownership of the AttributeSet and replaces it with a new empty AttributeSet.
* AttributeSet::removeAttribute(...) - releases the shared_ptr reference to a specific AttributeArray by index or name and returns it. There is also an "unsafe" variant that doesn't attempt to put the AttributeSet or Descriptor back into a valid state which is useful when you know the AttributeSet is being destroyed and want the extra performance.

OVDB-136: Attribute Stealing

---

CHANGES
doc/changes.txt
openvdb_houdini/SOP_OpenVDB_Combine.cc

Before the collation re-write, the VDB Combine would silently do nothing if the second input was empty and Flatten All B into A was toggled. The new drop down menu, however, errors in this case. By testing the b iterator, we can avoid generating a pair in this case and restore the previous behaviour.
Bug: 103362

VDB Combine in Flatten All mode shouldn't error with no second input

---

CMakeLists.txt
cmake/FindBlosc.cmake
cmake/FindCppUnit.cmake
cmake/FindIlmBase.cmake
cmake/FindLog4cplus.cmake
cmake/FindOpenEXR.cmake
cmake/FindOpenVDB.cmake
cmake/FindTBB.cmake
cmake/OpenVDBGLFW3Setup.cmake

Added CMake option `USE_PKGCONFIG` to the root level CMakeLists.txt, followed by checks inside `openvdb/cmake/*.cmake` files according to patch mentioned in #613 .
Signed-off-by: KartikShrivastava <shrivastavakartik19@gmail.com>

resolves #613 : Added CMake option to disable pkg-config

---

openvdb/math/Quat.h

as commented in #669 there doesn't seem to be a reason why quat inverse is const. Just made it const

labelling making quaternion inversion as const

---

.github/workflows/build.yml

This job has been sporadically failing on both Azure and Github Actions and is caused by running out of disk space on the virtual machine when building all the debug DSOs. Until recently, the VMs were generally providing more than their stated disk space, but that has been changed recently.
There are a few options to properly resolve this (which I hope we can discuss tomorrow), but for now, I think it's best to just disable this build.

Temporarily disable H18 debug build in CI

---

openvdb_houdini/ParmFactory.h

Include version.h rather than Platform.h.  The former will setup the ABI properly, and we now rely on ABI set properly for our destructor virtualization.  Otherwise missing ABI becomes old-school version, and we violate ODR on linking.

Include version.h rather than Platform.h.

---

openvdb_houdini/SOP_OpenVDB_From_Polygons.cc

The findfirstof can take a single char, which will be better than using a string of one character.

Use the single-character search rather than string search.

---

CHANGES
doc/changes.txt
openvdb/unittest/TestUtil.cc

As discussed, this PR fixes the util::CpuTimer unit test on Windows by using a more accurate sleep implementation.
This does **not** include any changes to the util::CpuTimer class itself - those will remain for further discussion/investigation in #690.

Fix CpuTimer Unit Test

---

openvdb_houdini/SOP_OpenVDB_Clip.cc
openvdb_houdini/SOP_OpenVDB_Fill.cc
openvdb_houdini/SOP_OpenVDB_Points_Group.cc
openvdb_houdini/SOP_OpenVDB_Rasterize_Points.cc
openvdb_houdini/SOP_OpenVDB_Read.cc
openvdb_houdini/SOP_OpenVDB_Remove_Divergence.cc

Addresses issue: Use GEO_Detail::getBBox Instead of GEO_Detail::computeQuickBounds #615
Signed-off-by: kubaroth <kubaroth@gmail.com>

Replace use of computeQuickBounds with getBBox.

---

.github/workflows/build.yml
ci/build.sh
ci/build_houdini.sh

Adds a new `DebugNoInfo` CMake build type which is kind of the opposite of `RelWithInfo`.
Switches the ABI7 debug build to use this build type (and switches the SSE42 build to release, not sure why it was ever set to debug).
I still can't switch on the Houdini debug build due to disk space issues. This can either be fixed in the short term by GitHub Actions resolving their current disk space issues (https://github.com/actions/virtual-environments/issues/709) or by stripping out some of the data in the Houdini install that we don't use (it is currently 4GB when uncompressed).

Use Debug Builds without Symbols to Fix CI

---

azure-pipelines.yml

As a result of changes in the hosted runners used in Azure Pipelines to more strictly enforce disk space limits, we're now hitting those limits even in release builds where we weren't before.
The Docker image is ~2.5GB and Houdini is ~4GB. For Azure Pipelines, we have access to just 10GB of disk space (GitHub Actions is 14GB) and I believe we're slightly over. This disables the unit tests and the command-line binaries for the Houdini build to reduce the disk footprint. Of course both of these components are still tested outside of the Houdini build. 
I'll look to re-enable these as we migrate the Houdini builds over to GitHub Actions with an improved mechanism, I just want to stabilise these builds for a little time first.

Disable binaries and unit tests for Houdini build

---

CHANGES
cmake/FindBlosc.cmake
cmake/FindCppUnit.cmake
cmake/FindIlmBase.cmake
cmake/FindJemalloc.cmake
cmake/FindLog4cplus.cmake
cmake/FindOpenEXR.cmake
cmake/FindOpenVDB.cmake
cmake/FindTBB.cmake
doc/changes.txt

This PR is a partial implementation of #654 
- Removing unnecessary DLL methods
- Adding better lib type detection on UNIX
- Added GNU path support
- Added required defines for static TBB on Windows
- Added required defines for static IlmBase and OpenEXR on Windows
- Improved handling of finding static builds of OpenVDB

Various improvements to CMake find modules

---

CHANGES
doc/changes.txt
openvdb/points/PointAttribute.h
openvdb/unittest/TestPointAttribute.cc

This is bug that's been in the codebase for some time - setting the uniform value in a new AttributeArray was skipped if it was equal to the default value (to save doing this redundant operation), however it should have been checking against the default value for this AttributeArray instance _not_ the generic default value for this value type.
This didn't show up until recently because default metadata wasn't being supported properly but that was resolved in #590. Thanks to Nick for reporting this one.

Fix AttributeArray Default Value Bug

---

CHANGES
doc/changes.txt
openvdb/points/AttributeArray.h

A new Clang compiler warning is detecting that the AttributeArray move constructor is being implicitly deleted due to the member mutex, despite it being marked as default. This shows up when using Apple Clang 11.0 (based off LLVM 8.0) that was introduced with Mac Catalina, and errors when OPENVDB_CXX_STRICT is enabled.

Fix move constructor compiler warning

---

openvdb/cmd/openvdb_lod.cc

Signed-off-by: Mark Sisson <5761292+marksisson@users.noreply.github.com>
Dynamic exception specification was deprecated in C++11, and removed in C++17.  This fixes compiler error when using C++17 compile feature by changing std::unexpected() to std::terminate().

change std::unexpected() to std::terminate()

---

.github/workflows/houdini.yml
ci/download_houdini2.py
ci/download_houdini2.sh
ci/install_houdini2.sh

This new Houdini GitHub Actions workflow runs once a week and does the following:
* Download the latest Houdini production build using the new SideFX download API and the stored secret keys
* Strip out the headers, libraries and binaries required for building the OpenVDB Houdini plugin
* Try and build the OpenVDB Houdini plugin
* If successful, insert it into the GitHub Actions cache
With this PR alone, nothing is actually using the cache - using it will come in a subsequent PR.
I set this up to run on Wednesdays prior to our TSC meetings in case issues come up that need discussing. The intention is to deprecate the old Houdini download and install scripts, but for the purposes of migration I've introduced new ones (ci/download_houdini2.py, etc). For now, I'm just adding Houdini 18.0.

Add Houdini CI caching workflow

---

.github/workflows/houdini.yml

The scheduled action ran as expected today and succeeded, however GitHub Actions cache v1 does not support reading or writing caches when using a "schedule" trigger. Bumping to v2 which does support this.

Bump Actions cache to v2

---

.github/workflows/build.yml
.github/workflows/docs.yml

Flip the logic in build and doc workflows to exclude certain paths (this should also correctly trigger builds on the new ax feature branch).

Update trigger rules for GitHub Actions

---

.github/workflows/houdini.yml
ci/download_houdini2.sh

The Houdini ABI test fails when attempting to use the Houdini cache due to a missing bzip library. Add this to Houdini cache and enable unit test evaluation to Houdini workflow.

Add bzip to houdini cache and evaluate unit tests

---

.github/workflows/build.yml
openvdb/unittest/TestTree.cc

This is mainly about switching on a CI build that uses GCC 9.3.1 which is the draft compiler for VFX Reference Platform 2021. In fact, there was only one build issue which was a missing default copy assignment operator in one of the unit tests (TestTree) that showed up as a compiler error with OPENVDB_CXX_STRICT set.
I haven't yet tried to enable C++17 or tried building the Houdini plugin, but it's a start.

Add VFX 2021 CI Build

---

.github/workflows/build.yml
ci/download_houdini2.sh
ci/install_houdini2.sh

This pulls the Houdini install from the GitHub Actions cache rather than attempting to download it directly. This side-steps all the issues with secret keys - once a week the Houdini install is updated in a regular scheduled job that _does_ have access to secret keys.
This is only for one job for now (the main Houdini 18.0 job). Once this has run successfully for a little while, I'll tidy up some of the old scripts, extend this to the other Houdini jobs and then finally deprecate Azure.

Fetch Houdini from cache

---

openvdb_houdini/SOP_OpenVDB_From_Polygons.cc

If we fail to retrieve the input mesh, we want to make the vector UI visible as we don't know if it is needed or not.  Otherwise it maintains the last set values which may cause it to become stuck off even though it is affecting the output.

Always set the vector UI to visible if we fail to get the input mesh.

---

.github/workflows/build.yml
ci/build.sh
ci/test_install.sh

Main change here is to leave the install directory to the system default so that the vdb install automatically ends up on the system path. Added this test to other ABI images and I'm looking to add this to the mac/windows CI asap too.

Improved test_install CI

---

.github/workflows/build.yml
ci/validate_houdini.sh

It should always have been downloaded from the GHA cache for the parent repo, but it is allowed to not exist on fork repos.

Add a check that ensures that Houdini is available in the ASWF repo

---

CHANGES
doc/changes.txt
openvdb_houdini/SOP_OpenVDB_From_Polygons.cc

Fixes the wrong parameter name being used.

A bad merge in PR747 grabbed the Houdini name for this parameter,

---

CHANGES
doc/changes.txt
openvdb/tree/InternalNode.h
openvdb/tree/LeafNode.h
openvdb/tree/RootNode.h
openvdb/unittest/TestLeaf.cc
openvdb/unittest/TestTree.cc

This follows the convention of using leafCount() to count the number of leaf nodes and addChild() to add an immediate child node. I added a unit test to cover the statistics methods in the leaf node too.

Add childCount() to RootNode, InternalNode and LeafNode

---

openvdb_houdini/SOP_OpenVDB_Points_Convert.cc

An automated linter had found a recommendation these be made const for efficiency.

const-correct some declarations

---

CHANGES
doc/changes.txt
openvdb/openvdb/Types.h
openvdb/openvdb/unittest/TestTypes.cc

Fixed an issue where `TypeList::Unique` would be instantiated continuously on every `TypeList`.
It seems that as soon as a `TypeList` of any kind is created, `TypeList::Unique` would also be instantiated. As this also creates a `TypeList` this causes the compiler to explode for larger lists. I tried changing the implementation of `TypeList::Unique` to use a different container but this doesn't help. Really the `Unique` typedef should be a separate template struct. However this fix stops automatic instantiation so it can continue to live on the `TypeList`.
See an example of the issue here:
https://github.com/Idclip/openvdb/runs/1101152129?check_suite_focus=true

TypeList::Unique compiler fix

---

CHANGES
doc/changes.txt
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Convert.cc

The OpenVDB Convert SOP would copy the meta data that might be out of date, so cause the name attribute to appear to revert to an earlier value.  This is similar to the fix done for the LOD SOP for a similar problem.

Synchronize Name attribute for OpenVDB Convert

---

nanovdb/nanovdb/NanoVDB.h

auto is not a valid return type in C++11. We either have to use decltype(auto)
or the explicit return type.
> 'auto' return without trailing return type; deduced return types are a C++14 extension
Signed-off-by: Stephan Seitz <stephan.seitz@fau.de>

Fix build of feature/nanovdb: explicit return type instead of auto

---

.github/workflows/build.yml
ci/install_macos.sh

boost python has been updated to use python 3.9, we were hard coding to 3.8

Fixed macos CI with automatic python selection

---

.github/workflows/houdini.yml
ci/download_houdini.sh

Boost 1.72 also needed the lzma library from the shipped Houdini libs, so this is now included in the cache.
After this has run for the first time in our weekly build, I'll update the CI to add an H18.5 build. We'll be dropping support for Houdini 17.5 with the imminent release of OpenVDB 8.0.

Add Houdini 18.5 to GitHub Actions Cache

---

cmake/OpenVDBGLFW3Setup.cmake

Fixes: https://github.com/AcademySoftwareFoundation/openvdb/actions/runs/398576400
I don't know why this explicit error was added

CMake 3.19 fix for find_package_handle_standard_args

---

.github/workflows/build.yml
CHANGES
doc/changes.txt
openvdb/openvdb/version.h

This addresses #902 and uses the apt package manager with ubuntu 20.04 to verify GCC10 and Clang10 both of which are now part of the GitHub Actions environment.

Add new GCC10 and Clang10 CI builds and fix size_t issue

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build---installation.md
.github/ISSUE_TEMPLATE/feature_request.md

I haven't modified these too much from the defaults github give you and haven't modified the "template chooser". You can see what these templates look like by creating an issue by clicking on "New Issue" in my fork: https://github.com/Idclip/openvdb/issues
More info:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository

Added github issue templates

---

CHANGES
doc/changes.txt
openvdb/openvdb/tree/NodeManager.h

This is a relatively rare issue accidentally introduced in #785 and picked up by @Idclip. It occurs when using non-thread-safe data members (such as a ValueAccessor) in a NodeManager foreach functor.

Fix determinism bug in NodeManager

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Combine.cc
pendingchanges/vdb_combine_avoid_bool.txt

Use a templated function to avoid invoking csg operations on bool
grids.  These aren't supported on MSVC as the unary negation operation
is invalid for bool.

Use a templated function to avoid invoking csg operations on bool

---

openvdb/openvdb/tools/Merge.h
openvdb/openvdb/unittest/TestMerge.cc
pendingchanges/fix_csg_intersection.txt

This isn't for final review as it needs a bit more work, but it resolves the issue and demonstrates that it doesn't require changes to the DynamicNodeManager.
As you identified @jmlait, the issue is that for the root node in CSG intersection mode, if any trees being merged don't have a particular key, that element needs to be deleted from the resulting tree, meaning unlike CSG union and CSG difference, _absence_ of a root node child takes precedence over outside/inside tiles or child nodes. This doesn't apply to InternalNodes in CSG intersection mode as every element must be either a tile or a child.
I took a slightly different approach to yours here and first detect any keys that need deleting from the target tree, then delete them. Adding tiles or children in CSG intersection mode is …

Fix CSG intersection

---

.github/workflows/build.yml

Although we don't officially support VFX Reference 2018, our codebase seems to still build against it, so I suggest we keep this test for the time being. When we deprecate support for Houdini 18.0 later this year, we can jump to VFX Reference 2020 as our minimum supported version - which will make Boost 1.70 our minimum version.

Run CI against VFX Ref 2018

---

CMakeLists.txt
README.md
cmake/FindOpenVDB.cmake
doc/build.txt
doc/dependencies.txt
openvdb/openvdb/BuildConfig.h.in
openvdb/openvdb/CMakeLists.txt
openvdb/openvdb/Types.h
openvdb/openvdb/math/Half.cc
openvdb/openvdb/math/Half.h
openvdb/openvdb/math/HalfLimits.h
openvdb_ax/openvdb_ax/CMakeLists.txt

- Removed `USE_EXR` and other variants in favour of `USE_IMATH_HALF`
- Updated FindOpenVDB.cmake to work with new half requirement
- Removed EXR RPATHS
- Updated documentation
- Capitalized headers in math/

Half CMake Improvements

---

openvdb_houdini/openvdb_houdini/PointUtils.cc

I think this was already checked on parent caller, so wouldn't show
up in the wild, but is clearly wrong.

Avoid a dereference of an attribute that we know to be null.

---

openvdb/openvdb/unittest/TestStreamCompression.cc
pendingchanges/fix_stream_compression_test.txt

This unit test is designed to pass a sequence of 32 integers to Blosc that cannot be compressed to test the failure case in our library, however the random shuffling wasn't being seeded correctly so it was generating a different sequence every time and sporadically failing.
I've replaced the random shuffle with a hard-coded deterministic sequence that always fails to compress instead.

Fix Stream Compression Unit Test

---

openvdb/openvdb/tools/Activate.h
openvdb/openvdb/unittest/TestActivate.cc
openvdb/openvdb/unittest/TestTools.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Activate.cc
pendingchanges/vdb_activate.txt

I've introduced a new TestActivate unit test to test all the different parts of the `tools::activate()`/`tools::deactivate()` and introduced some other improvements.
I ported `tools::activate()`/`tools::deactivate()` from using `tools::foreach()` and the TreeIterator to use the DynamicNodeManager. This makes activation around 4x faster and deactivation around 1.5x faster. Here's a quick breakdown of a benchmark (included in the new unit test):
Foreach/TreeIterator:
* Activate Leaf - 1 second 141 milliseconds
* Activate Tile - 1 second 878 milliseconds
* Deactivate Leaf - 1 second 494 milliseconds
* Deactivate Tile - 299 milliseconds
DynamicNodeManager:
* Activate Leaf - 719 milliseconds
* Activate Tile - 39 milliseconds
* Deactivate Leaf - 1 second 205 milliseconds
* Deactivate Tile - 16 …

Activate/Deactivate Improvements

---

openvdb/openvdb/tree/NodeManager.h
pendingchanges/node_manager_ref.txt

In #921, I reverted the change to the NodeManager foreach methods to use copy-by-value instead of copy-by-reference. As it turns out this has a significant performance cost for the DynamicNodeManager that would take a lot of extra complexity in the API to resolve. This now forks the implementation so that NodeManager foreach uses copy-by-value and DynamicNodeManager foreach uses copy-by-reference.
I had tried to keep these two structures as aligned as possible, but they have already diverged because the DynamicNodeManager passes an index to the operator() and returns a bool whereas the NodeManager does not. This is not ideal, but I think is probably the most pragmatic way of resolving this.

Fix Performance Regression in DynamicNodeManager

---

openvdb_houdini/openvdb_houdini/AttributeTransferUtil.h
openvdb_houdini/openvdb_houdini/GeometryUtil.cc
pendingchanges/fix_vector_reserve.txt

Fix for uninitialised memory use in Convert VDB SOP.
Unlike UT_Array, std::vector sets the size not the capacity with the constructor.

Fix for uninitialised memory use in Convert VDB SOP

---

doc/examplecode.txt
openvdb/openvdb/Grid.cc
openvdb/openvdb/Metadata.cc
openvdb/openvdb/io/Archive.cc
openvdb/openvdb/io/Queue.cc
openvdb/openvdb/math/Maps.cc
openvdb/openvdb/openvdb.cc
openvdb/openvdb/points/AttributeArray.cc
openvdb/openvdb/points/AttributeArray.h
openvdb/openvdb/python/pyutil.h
openvdb/openvdb/tools/FastSweeping.h
openvdb/openvdb/tools/PointIndexGrid.h
openvdb/openvdb/tree/LeafBuffer.h
openvdb/openvdb/unittest/TestAttributeArray.cc
openvdb/openvdb/unittest/TestPointMove.cc
openvdb/openvdb/unittest/TestStreamCompression.cc
openvdb/openvdb/unittest/TestTools.cc
openvdb/openvdb/util/PagedArray.h
openvdb/openvdb/viewer/Viewer.cc
openvdb_houdini/openvdb_houdini/GR_PrimVDBPoints.cc
openvdb_houdini/openvdb_houdini/SOP_NodeVDB.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Rasterize_Points.cc
openvdb_maya/openvdb_maya/OpenVDBPlugin.cc

Should I keep the commit that removes these `using` declarations,
```
using Mutex = std::mutex;	
using Lock = std::lock_guard<Mutex>;	
```
in favor of directly using the std types? Or would you like to keep these `using` declarations?

Issue 887/switch to std::atomic and std::mutex from deprecated tbb versions

---

openvdb/openvdb/tree/NodeManager.h
openvdb/openvdb/unittest/TestNodeManager.cc
pendingchanges/node_manager_const.txt

Despite the additional filtering cost, I've found that there's a small performance improvement (~5%) using a DynamicNodeManager with a const tree instead of a NodeManager. This won't necessarily apply for all workflows and it's small enough an improvement to not be statistically significant. Nonetheless, this change extends the DynamicNodeManager so that it can work with const trees.
My best guess as to a potential rationale is that it could be related to using copy-by-reference in the DynamicNodeManager instead of copy-by-value or some caching effect of interleaving the building of linear node arrays and evaluating over those node arrays (the NodeManager builds all node arrays up-front).

Extend DynamicNodeManager to work with Const Trees

---

.github/workflows/sanitizers.yml
CMakeLists.txt
cmake/config/OpenVDBBuildTypes.cmake

Adds support for address, memory, thread and UB sanitizers and reworks the coverage option
An example run: https://github.com/Idclip/openvdb/actions/runs/679869827

CI Sanitizers

---

openvdb/openvdb/CMakeLists.txt
openvdb/openvdb/tools/NodeVisitor.h
openvdb/openvdb/tree/Tree.h
openvdb/openvdb/unittest/CMakeLists.txt
openvdb/openvdb/unittest/TestNodeVisitor.cc
pendingchanges/node_visitor.txt

As requested by @jmlait, this tool provides the ability to visit nodes in a single-threaded, depth-first order. It's the functionality that's currently missing to allow us to remove the Tree::visit() methods.
It's a pretty small amount of code, most of the changes here are documentation and unit tests.  In fact, I used the sub-tree functionality here in the upcoming density VDB merging and it was quite useful.

New NodeVisitor Tool

---

ci/extract_test_examples.sh
doc/ax/ax.txt
doc/ax/axcplusplus.txt
doc/ax/axexamples.txt

- Improved AX examples in doxygen documentation
- Updated `ci/extract_test_examples.sh` to also compile AX code in documentation (would previously just parse)
@richhones

Updated AX example docs

---

openvdb/openvdb/unittest/CMakeLists.txt
pendingchanges/openvdbtests.txt

I very frequently do not wish to build all the unit tests and only wish to iterate on one or even a few. Right now, this requires modifying the CMakeLists.txt for the unit tests and carefully managing this edit, so as not to commit this change.
This PR adds a new optional CMake variable to define the unit tests you wish to build such as:
cmake -DOPENVDB_TESTS=NodeManager
cmake -DOPENVDB_TESTS="Activate;NodeManager"
If this variable isn't provided by the user, all the unit tests will be built. You'll note that this list assumes the format "Test<Name>.cc" which is our convention.

Add optional CMake variable to build a subset of the unit tests

---

openvdb/openvdb/points/PointAttribute.h
openvdb/openvdb/points/PointConversion.h
openvdb/openvdb/points/PointDataGrid.h
openvdb/openvdb/points/PointGroup.h
openvdb/openvdb/points/PointMove.h
openvdb/openvdb/unittest/CMakeLists.txt
openvdb/openvdb/unittest/TestPointInstantiate.cc
openvdb_houdini/openvdb_houdini/VRAY_OpenVDB_Points.cc
pendingchanges/point_aliases.txt

This fixes all cases where PointIndexTree, PointDataGrid and PointDataTree were used incorrectly instead of the templated T type and also renames any templated typenames that would override these aliases.
Finally, I have added a new unit test that builds a custom PointDataGrid with a different value type and leaf node size and added a macro to disable the PointDataGrid and PointDataTree aliases to ensure that the functionality in the headers only ever uses templated types.

Fix PointData and PointIndex aliases

---

openvdb/openvdb/points/PointCount.h
openvdb/openvdb/unittest/TestPointCount.cc
pendingchanges/point_offsets.txt

bugfix when calling points::pointOffsets with an empty grid

---

openvdb/openvdb/Platform.h
openvdb/openvdb/points/AttributeArray.h
openvdb/openvdb/tools/FindActiveValues.h
openvdb/openvdb/tools/Morphology.h
openvdb/openvdb/tree/LeafManager.h
openvdb/openvdb/tree/Tree.h
openvdb/openvdb/util/PagedArray.h
pendingchanges/deprecation_macro.txt

This macro controls the C++ standard `[[deprecated]]` attribute's behaviour.

Re-introduced the OPENVDB_DEPRECATED macros

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_AX.cc
pendingchanges/ax_sop_empty.txt

This fixes a bug where the AX Houdini SOP would crash using an empty points grid as input.

Bugfix for empty points in AX SOP

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Activate.cc
pendingchanges/vdbactivateworldspace.txt

VDB Activate is also switched to working with tiles, which changes behaviour
but the old behaviour is likely a bug.  Houdini's version will also make
this change.

Support for worldspace dilation specification in the VDB Activate SOP.

---

ci/install_macos.sh

brew now uses OpenEXR 3 which we don't yet support

Lock macos CI to openexr@2

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Rebuild_Level_Set.cc
pendingchanges/vdb_rebuild_sdf_meta.txt

This showed up in Houdini where using the VDB Rebuild SDF SOP was resulting in a VDB primitive that was returning a value of "" for the vdb_value_type intrinsic instead of "float".
I believe the expectation here is that the VDB Rebuild SDF SOP should behave like the VDB Renormalize SDF SOP and carry across metadata from the input grid. The language here "Repair level sets represented by VDB volumes" leads me to believe that this SOP is modifying the input grid rather than creating a new grid. 
The alternative is perhaps to follow the example of SOPs like the VDB Resample SOP which copies across attributes and group membership by using `hvdb::replaceVdbPrimitive()` and then reconstructs the metadata.

Fix VDB Rebuild SDF SOP Metadata

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Resample.cc
pendingchanges/vdb_resample_voxel_size.txt

Both of these modes have text such as this in the help:
> Using Voxel Scale Only
> 
> Keep the transform of the input VDB but scale the voxel size, increasing or decreasing the resolution.
However, the VDB Resample SOP was always creating a new linear transform and applying the voxel size/scale. This fix takes the transform from the input VDB as I believe was intended.

Fix VDB Resample SOP - Voxel Size + Voxel Scale

---

openvdb_ax/openvdb_ax/test/backend/util.h

Fixes build issues with the AX unit tests with LLVM 11 & 12

Added missing unittest include

---

openvdb/openvdb/points/points.cc
openvdb/openvdb/unittest/TestAttributeArray.cc
pendingchanges/point_unit_types.txt

These attribute types are used by Houdini and should be registered by default.

Add 8-bit and 16-bit unit attribute registration

---

tsc/process/release.md

Mostly reorganisation - I solidified the release candidate process into this doc and moved the "preparing for the next release" section up into the release candidate branching step. Also, updated the link for the docs action to jump straight to the manual dispatch.

Update release process to include release candidate

---

openvdb_ax/openvdb_ax/test/compiler/TestVolumeExecutable.cc

The AX unit tests failed for me because it looks like I've been building against a version of CppUnit that has sstream support disabled. This has worked for many years when OpenVDB was using CppUnit and the fix is pretty simple - to use `CPPUNIT_ASSERT(a == b)` instead of `CPPUNIT_ASSERT_EQUAL(a, b)` for enums.

Modify AX unit tests to build against CppUnit without sstream

---

.github/workflows/ax.yml
ci/install_macos.sh
ci/install_macos_ax.sh
openvdb/openvdb/version.h.in

We noticed our internal build was setting OPENVDB_USE_BLOSC, which then conflicted with the version.h.  The intent of the version.h was not to get in the way of people with explicit -D command lines, so thus have disabled it in this fashion.
I'm hesitant to remove from our build command line as then we'll fail if we revert openvdb at any point...

Guard the cmakedefines in case systems have -D options

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Vector_Merge.cc
pendingchanges/rename_vdbvectormerge_sop.txt

Internal review found this the least objectionable new name, but it
is up to the TSC if it meets our standards.  Only the label is changed,
I believe I have preserved the internal names properly.

Rename VDB Vector Merge to VDB Vector from Scalar

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/houdini.yml
.github/workflows/houdini_cache_update.yml
.github/workflows/sanitizers.yml
.github/workflows/whitespace.yml
ci/build.sh
ci/build_windows.sh

- Improved the usage of various actions
- Bumped ubuntu images to latest
- Simplified the ./build scripts to not use arbitrary positional arguments
- Introduced a `linux-extra` build matrix in `build.yml` which includes various jobs which are designed to test different build types outside the standard build types. This includes the existing `NO_BLOSC`, `SSE` and `USE_IMATH` builds. Added an `AVX` build. In an attempt to speed up builds, these builds only build weekly, not on commit.
- Various tweaks to improve the speed of some of the configurations
- Don't trigger any CI if `pendingchanges/**` changes

Various CI improvements

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Combine.cc
pendingchanges/vdbcombinefix.txt

If needA is false, agrid likely doesn't exist, so we should just
dispatch on the bgrid rather than try to verify a and b have
the same type.  I believe the old code would have ignored the passed
in agrid in this case.

Fix a bug that crept in when we switched dispatchers.

---

openvdb/openvdb/math/Stencils.h
openvdb/openvdb/tools/Filter.h
openvdb/openvdb/tools/LevelSetFilter.h
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Filter.cc

Resubmission of Peter's sharpening work from #455. 
@Idclip - As noted below, this does unfortunately add a new boost dependency that wasn't there before, I couldn't see a trivial way of stripping this out. :(
- Added tools::Filter::sharpen().
- Moved sharpeningKernel() from LevelSetFilter.h to Stencils.h,
for use by both Filter and LevelSetFilter.
- Changed BaseStencil::BufferType to boost::container::vector<T>
to work around the absence of std::vector<bool>::data().
- Added a Sharpen option to the Filter SOP.

OVDB-101: Extended sharpening support to non-level-set volumes.

---

openvdb/openvdb/tools/FastSweeping.h
pendingchanges/fast_sweep_improvement.txt

Invoke single call to dilateActiveValues ~10% faster

---

openvdb/openvdb/unittest/TestFastSweeping.cc

Changing various parameters used in the Fast Sweeping unit test. My debug build in the studio results in the following number:
- old run time = 50392 ms
- new run time = 5194 ms,

Update Test Fast Sweeping to run faster.

---

openvdb/openvdb/math/Math.h

When no attribute type is specified, an attribute grid with value type size_t
is defined. This attribute grid is not actually used and size_t is merely used
because some value type has to be provided.
Depending on the platform and compiler, using size_t could lead to build errors
since it's not a typical value type used for OpenVDB grids.
Instead arbitrarily pick int32_t as a value type that is known to be supported.

Fix build error using ParticlesToLevelSet without attribute

---

openvdb/openvdb/tree/NodeManager.h
openvdb/openvdb/unittest/TestNodeManager.cc
pendingchanges/nodemanagergrainsize.txt

After some consideration, I decided to make the current grain size apply only to threading across leaf nodes and to add an additional grain size to thread across non-leaf nodes.
For most cases, adjusting the grain size for the leaf node threading is what you want, but at least with this implementation there's the option to provide an additional grain size for internal node threading rather than having this hard-coded to any particular value. By default, non-leaf node threading is set to 1.

DynamicNodeManager Grain Size

---

.github/workflows/build.yml
.github/workflows/houdini.yml
.github/workflows/houdini_cache_update.yml

This also officially drops CI support for Houdini 18.0.

Updating CI for CY2022 Reference Platform

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_LOD.cc
pendingchanges/vdblod_metadata.txt

The VDB LOD SOP can output grids with either int64 or float metadata with the same name ("MultiResGrid_Level") depending on the mode used. This fix is to address an issue reported in production where it's not possible to chain two VDB LOD SOPs with different modes. You can replicate by using one VDB LOD SOP with mode == "single level" and another connected to it with mode == "LOD Pyramid" or vice-versa.
In this case, it now checks whether the metadata already exists on the input grid and is of an incompatible type and then drops that metadata before calling the MultiResGrid code.
Note that I only fixed for ABI>=7 because we're soon to remove support for older ABIs / Houdini versions anyway.

Fix bug with VDB LOD SOP Chaining

---

openvdb_houdini/openvdb_houdini/CMakeLists.txt
pendingchanges/houdini_dso_names.txt

This PR (#1025) has been really useful to me, so adding a similar option to control Houdini DSOs as well.
`cmake -DOPENVDB_DSO_NAMES=SOP_OpenVDB_Activate ..`
`cmake -DOPENVDB_DSO_NAMES="SOP_OpenVDB_Activate;SOP_OpenVDB_Resample" ..`

Add optional CMake variable to build a subset of the Houdini DSOs

---

openvdb/openvdb/tree/InternalNode.h
openvdb/openvdb/tree/LeafNode.h
openvdb/openvdb/tree/LeafNodeBool.h
openvdb/openvdb/tree/LeafNodeMask.h
openvdb/openvdb/tree/RootNode.h
openvdb/openvdb/unittest/TestLeaf.cc
openvdb/openvdb/unittest/TestLeafBool.cc
openvdb/openvdb/unittest/TestLeafMask.cc
openvdb/openvdb/unittest/TestTree.cc
pendingchanges/blind_data.txt

Adding a transitive offset to the RootNode, InternalNode and LeafNodes. This is an ABI=9 feature and doesn't change the size of the nodes in memory, just adds a 32-bit integer to each.
I hesitated on the naming and decided to call this a "transitive offset" - we use offset quite frequently in various contexts and making the transitive nature of this explicit seemed like a good idea.
The other aspect I hesitated on is the size of the integer type. In this implementation, the underlying size is a 32-bit integer (so as not the need to expand the node), but input and output is a 64-bit integer. As mentioned previously, we can steal a few unused bits from the origin to stretch the size of the offset we can store - by making the interface 64-bit, this saves needing to make an ABI change at a …

Blind Data (ABI=9)

---

cmake/OpenVDBHoudiniSetup.cmake
pendingchanges/houdini_abi8.txt

As reported by @plattfot in issue #1172.
I've slightly tweaked the logic here so that it compares with the major.minor version of Houdini and thus doesn't require us to make any assumptions about which version of Houdini that SideFX might ship next, so that we can opt to extend this as soon as we enter a new calendar year.

Set ABI=8 as default for Houdini and lock H18.5 to ABI=7

---

openvdb_houdini/openvdb_houdini/GEO_PrimVDB.cc
openvdb_houdini/openvdb_houdini/GEO_PrimVDB.h
openvdb_houdini/openvdb_houdini/GEO_VDBTranslator.cc
openvdb_houdini/openvdb_houdini/GU_PrimVDB.cc

This includes CE grid support (From 18.5 but last sync Nano wasn't official
yet)
The one real change (which isn't just FYI/reference) is to GEO_VDBTranslator
to ignore empty vdbs when building bounding boxes.  We were enlarging
the final stat by the min/max of the bbox, but for invalid boxes that
obviously will be wrong.  This showed up as the File SOP load-as-info
giving huge bounding boxes if an empty vdb was present.

Synchronization of these files with H19.

---

.github/workflows/houdini.yml
.github/workflows/houdini_cache_update.yml
CMakeLists.txt
ci/install_cmake.sh
openvdb/openvdb/CMakeLists.txt
openvdb/openvdb/cmd/CMakeLists.txt
openvdb/openvdb/python/CMakeLists.txt
openvdb/openvdb/unittest/CMakeLists.txt
openvdb_ax/openvdb_ax/CMakeLists.txt
openvdb_ax/openvdb_ax/cmd/CMakeLists.txt
openvdb_houdini/openvdb_houdini/CMakeLists.txt
openvdb_maya/openvdb_maya/CMakeLists.txt

- Removed explicit RPATHs in favour of CMake's automatic behaviour
- Changed the Houdini CI to extract the Houdini install outside the OpenVDB root source to fix CMake install RPATHs being ignored
- Changed the include order for VDB dependencies to better resolve issues where system libraries would conflict
- Download CMake rather than building from source (saves ~5min)

RPATH and Houdini improvements

---

cmake/OpenVDBHoudiniSetup.cmake

During cmake configuration if `Houdini_VERSION_MAJOR_MINOR` is greater than or equal to 19.0 it will extract the ABI version number from `openvdb/version.h` shipped with Houdini.
If it fails it will use the similar fallback as before, except it will use `OpenVDB_MAJOR_VERSION` instead of hardcoded `8`.
Signed-off-by: Fredrik Salomonsson <fredriks@d2.com>

Auto detect OpenVDB API for houdini-19+

---

cmake/FindOpenVDB.cmake

I've changed `OpenVDB_FIND_QUIET` to `OpenVDB_FIND_QUIETLY`. It fixes a typo, as the [docs](https://cmake.org/cmake/help/latest/command/find_package.html) say that:
> When loading a find module or package configuration file find_package defines variables to provide information about the call arguments (and restores their original state before returning):
> 
> ...
> 
> \<PackageName\>_FIND_QUIETLY
> True if QUIET option was given

Fix typo in cmake/FindOpenVDB.cmake to handle the QUIET argument of find_package() correctly

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/houdini.yml

This introduces ccache to Linux release builds including AX and Houdini (12 jobs in total). An identical (re)build now takes around 12 hours less cumulatively and costs 692MB in disk space.

Introduce ccache to Linux release builds

---

.github/workflows/houdini.yml

On exit of any Houdini job, the houdini cache will be re-saved as a new cache tarball. This circumvents this behavior by storing it as an empty dummy cache instead.

Use an empty dummy cache to re-save the Houdini cache on exit

---

nanovdb/nanovdb/NanoVDB.h
nanovdb/nanovdb/util/SampleFromVoxels.h

We are using HIP in Blender/Cycles for AMD GPU rendering, and some small changes are needed to make NanoVDB work.
https://github.com/ROCm-Developer-Tools/HIP
* Use host/device qualifiers when either `__CUDACC__` or `__HIP__` is defined
* Add `__hostdev__` to method definitions outside the class body. CUDA only needs them in the class body declaration, but HIP needs both.
This makes using the NanoVDB headers as part of HIP C++ code work. It does not add support for HIP to the examples. That would be a much bigger change and likely add much code duplication.

And HIP support for NanoVDB

---

CHANGES

Updated CHANGES with a new feature, namely support for HIP in NanoVDB

Updated CHANGES

---

.github/workflows/houdini.yml

This updates the cache keys, adds the dummy cache workflow and eliminates H18.0 builds as we no longer store Houdini 18.0 caches.

Update v8.2 branch to use new houdini caches

---

openvdb/openvdb/tools/PointAdvect.h

Signed-off-by: Edward Lam <edward@sidefx.com>

Remove unused tbb/task.h include to avoid deprecation warnings

---

README.md
ci/install_windows.sh
cmake/FindOpenVDB.cmake
doc/build.txt
doc/dependencies.txt
openvdb/openvdb/CMakeLists.txt
openvdb/openvdb/unittest/TestStreamCompression.cc

This library dependency was not being used anywhere, and therefore
adding an additional dependency to the whole build system for no reason.
Signed-off-by: Ignacio Vizzo <ignaciovizzo@gmail.com>

Remove unnecessary boost system dependency

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Merge.cc
pendingchanges/vdbmerge_fix.txt

The vdbPrimsToRemove in MergeOp is shared across threads,
so calling push_back resulted in race conditions and the prims
occasionally not being deleted or the std::dequeue becoming
corrupt and crashing.
Made the simplest change of just switching to a UT_ConcurrentVector
that wraps the tbb structure.
A more correct change would be to return vdbPrimsToRemove like we
do the outputgrids so we could explicitly gather them without locking,
this would also avoid this unseen action at distance.

The vdbPrimsToRemove in MergeOp is shared across threads,

---

cmake/FindBlosc.cmake

Fixed FindBlosc.cmake on Windows with vcpkg changes to zstd

---

openvdb/openvdb/tools/Count.h
openvdb/openvdb/unittest/TestCount.cc

A thread that doesn't visit a valid value would run an invalid join() op

Fixed a bug in new minMax()

---

.github/workflows/build.yml
.github/workflows/weekly.yml
cmake/scripts/ubsan.supp
openvdb/openvdb/math/Coord.h
openvdb/openvdb/math/Math.h
openvdb/openvdb/tree/LeafBuffer.h
openvdb/openvdb/unittest/CMakeLists.txt
openvdb/openvdb/unittest/TestCoord.cc
openvdb/openvdb/unittest/TestIndexIterator.cc
openvdb/openvdb/unittest/TestPointConversion.cc
openvdb_ax/openvdb_ax/test/CMakeLists.txt

Updated the UBSAN builds to actually be useful - i.e. they now fail if they find an issue. I removed NanoVDB as part of this as NanoVDB had a lot of warnings.
As part of this I fixed a few issues and suppressed the rest. Most of the suppressions are required in tbb, the ones in VDB as predominately due to left shifts of negative numbers.

Updated UBSAN builds to fail on errors

---

cmake/FindOpenVDB.cmake

FindPythonLibs deprecated since cmake version 3.12. Use the `FindPython` module instead. More information about this change in the [official cmake documentation](https://cmake.org/cmake/help/v3.15/module/FindPythonLibs.html)
```cmake
cmake_minimum_required(VERSION 3.15)
project(test_project)
include(GNUInstallDirs)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_FULL_LIBDIR}/cmake/OpenVDB")
find_package(pybind11 REQUIRED)
find_package(OpenVDB COMPONENTS REQUIRED pyopenvdb)
add_executable(main main.cpp)
target_link_libraries(main OpenVDB::pyopenvdb)
```
```sh
cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/cc - …
```

Fix pyopenvdb build support

---

openvdb/openvdb/CMakeLists.txt
openvdb/openvdb/points/PointCount.h
openvdb/openvdb/points/PointMask.h
openvdb/openvdb/points/PointRasterizeSDF.h
openvdb/openvdb/points/PointRasterizeTrilinear.h
openvdb/openvdb/points/PointTransfer.h
openvdb/openvdb/unittest/CMakeLists.txt
openvdb/openvdb/unittest/TestPointMask.cc
openvdb/openvdb/unittest/TestPointRasterizeSDF.cc
openvdb/openvdb/unittest/TestPointRasterizeTrilinear.cc

This is a draft pull request of the point transfer/rasterization framework and spherical, ZB and trilinear kernels. The final commit adds a dummy Houdini SOP which can be used to test the surfacing methods in Houdini, but I anticipate this to be left out of a final PR. Note that this PR also includes the PointStatistics #997 work.
Below are some preliminary timings. More data to be added (timings, images of results, surface comparisons etc).
**Input**: https://artifacts.aswf.io/io/aswf/openvdb/models/waterfall_points.vdb/1.0.0/waterfall_points.vdb-1.0.0.zip
----------------------------------------------------------------------------------------------------------------------------------------------
`tools::rasterizeSpheres()` vs `tools::ParticlesToLevelSet` (From Particle SOP)
No attribute …

OpenVDB Points -> Volume transfer framework & kernels

---

openvdb/openvdb/python/CMakeLists.txt
openvdb/openvdb/python/test/TestOpenVDB.py
pendingchanges/cmake_boost_python.txt

This addresses an issue where:
```
find_package(Boost COMPONENTS pythonXY)
```
Creates a broken `Boost::python` target on some implementation which subsequently stops other searches. This breaks our technique of progressively searching for boost targets should one fail i.e:
```
find_package(Boost COMPONENTS pythonXY)
find_package(Boost COMPONENTS pythonX)
find_package(Boost COMPONENTS python)
```
These changes should continue to support some of this behaviour but also exposes options for users to control how boost python is found. That being said, the boost cmake situation is a mess and I'd rather spend any time in this area trying to transition to pybind as fast as possible.

Boost python CMake changes

---

CMakeLists.txt
ci/build.sh
cmake/OpenVDBHoudiniSetup.cmake
cmake/config/OpenVDBCXX.cmake
cmake/config/OpenVDBVersions.cmake
nanovdb/nanovdb/util/NanoToOpenVDB.h
nanovdb/nanovdb/util/OpenToNanoVDB.h
openvdb/openvdb/Grid.h
openvdb/openvdb/openvdb.cc
openvdb/openvdb/points/AttributeArray.cc
openvdb/openvdb/points/AttributeArray.h
openvdb/openvdb/tree/Tree.h
openvdb/openvdb/unittest/TestGrid.cc
openvdb/openvdb/unittest/TestNodeVisitor.cc
openvdb/openvdb/unittest/TestTree.cc
openvdb/openvdb/version.h.in
openvdb_houdini/openvdb_houdini/ParmFactory.h
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_LOD.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Visualize.cc

- Removed deprecated options, code paths and ABI 6
- Deprecated ABI 8
- Moved MINIMUM version defines to cmake/config/OpenVDBVersions.cmake
- Renamed OpenVDBBuildTypes.cmake to OpenVDBCXX.cmake
- Moved other CMake CXX options to OpenVDBCXX.cmake
- Added deprecation warnings for C++14, CMake and Houdini

CMake updates:

---

openvdb_ax/openvdb_ax/ast/Parse.cc
openvdb_ax/openvdb_ax/ast/Parse.h
openvdb_ax/openvdb_ax/ax.cc
openvdb_ax/openvdb_ax/codegen/ComputeGenerator.cc
openvdb_ax/openvdb_ax/codegen/PointComputeGenerator.cc
openvdb_ax/openvdb_ax/codegen/VolumeComputeGenerator.cc
openvdb_ax/openvdb_ax/compiler/Compiler.cc
openvdb_ax/openvdb_ax/compiler/Compiler.h
openvdb_ax/openvdb_ax/compiler/Logger.cc
openvdb_ax/openvdb_ax/compiler/Logger.h
openvdb_ax/openvdb_ax/test/backend/TestLogger.cc
openvdb_ax/openvdb_ax/test/compiler/TestAXRun.cc
openvdb_ax/openvdb_ax/test/compiler/TestPointExecutable.cc
openvdb_ax/openvdb_ax/test/compiler/TestVolumeExecutable.cc
openvdb_ax/openvdb_ax/test/frontend/TestSyntaxFailures.cc
openvdb_ax/openvdb_ax/test/util.h
pendingchanges/ax_fixes.txt

- Fixed a regression in ax::run which wouldn't propagate exceptions
- Improved logger exit handling in the compiler
- Improved the behaviour of ax::parse for invalid ASTs

Various AX improvements

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Activate.cc
pendingchanges/vdbactivate_continue.txt

The correct thing is just to ignore these prims.

VDB Activate SOP for no good reason bailed out as soon as a non-vdb was found

---

openvdb/openvdb/unittest/TestPointRasterizeFrustum.cc

This fixes an issue only tested in the weekly CI builds.

Disable frustum rasterization memory tests if blosc or delayed loading not in use

---

openvdb/openvdb/points/PointRasterizeFrustum.h
openvdb/openvdb/points/impl/PointRasterizeFrustumImpl.h

This fixes a tbb issue when building against the latest TBB and was picked up by the macos11 builder.

Migrate to thread::cancelGroupExecution

---

openvdb/openvdb/math/Math.h

On Windows, labs() uses long which is int32_t instead of int64_t so we
were silently casting down in math::isUlpsEqual(). Since C++11, there
have been proper overloads of std::abs() for both long and long long
provided by `<cstdlib>` so just use that instead.
Signed-off-by: Edward Lam <edward@sidefx.com>

Sweep out use of labs() from openvdb/Math.h

---

openvdb/openvdb/math/Math.h
openvdb/openvdb/math/Tuple.h

Fixes #1419 
Also removed lookup table implementation of Min/MaxIndex which is about twice as slow as a trivial loop

Minor improvements to some methods in Math.h

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Clip.cc

This makes it clear it is a bounding box clip, not a geometry clip.  Matches upcoming 19.5 rename.

Rename label of menu item for clipping by geometry

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Visualize.cc
pendingchanges/vdb_visualize_clamp.txt

When displaying voxels or points as colors, the input value is not being clamped to the range, so it wraps around. This fixes that by applying the clamp before evaluating the UT_Ramp.

Fix clamp bug in VDB Visualize SOP

---

openvdb/openvdb/tools/Merge.h
openvdb/openvdb/unittest/TestMerge.cc
pendingchanges/sum_merge_fixes.txt

There are two issues being addressed here - one produces incorrect results when deep-copying nodes from the source tree as the mask tree that stores the updated topology of the const input tree is being pruned at the wrong level, the other produces incorrect results for grids which have non-zero background values.
There's also some minor refactoring and a couple of additions to the merge API in preparation for adding maximum mode.

Fix issues in merge tool when using sum mode

---

openvdb/openvdb/tools/ValueTransformer.h
openvdb/openvdb/tree/Tree.h

This is no longer needed in VS2019, and out right errors with
/permissive- enabled.

Remove obsolete #ifndef _WIN32 code paths.

---

openvdb/openvdb/tools/Morphology.h

For some unknown reason MSVC /permissive- has problems with correctly
inferring the LeafT here due to it being used with different types in
the same function. Changing it from LeafT to auto instead allows it
to compile.

Fix VS2019/VS2022 compiler error in Morphology.h

---

doc/examplecode.txt
doc/math.txt
nanovdb/nanovdb/examples/benchmark/Benchmark.cc
nanovdb/nanovdb/unittest/TestOpenVDB.cc
openvdb/openvdb/Platform.h
openvdb/openvdb/math/Mat.h
openvdb/openvdb/tools/RayTracer.h
openvdb/openvdb/tools/ValueTransformer.h
openvdb/openvdb/unittest/TestGridTransformer.cc
openvdb/openvdb/unittest/TestMaps.cc
openvdb/openvdb/unittest/TestPointAdvect.cc
openvdb/openvdb/unittest/TestPointConversion.cc
openvdb/openvdb/unittest/TestPointCount.cc
openvdb/openvdb/unittest/TestPointDataLeaf.cc
openvdb/openvdb/unittest/TestPrePostAPI.cc
openvdb/openvdb/unittest/TestQuantizedUnitVec.cc
openvdb/openvdb/unittest/TestQuat.cc
openvdb/openvdb/unittest/TestRay.cc
openvdb/openvdb/unittest/TestTools.cc
openvdb/openvdb/unittest/util.h
openvdb_cmd/vdb_view/Camera.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Resample.cc
pendingchanges/msvc_use_math_defines.txt

Replace M_PI* constants with openvdb::math::pi<T>(). This allows us to
remove the reliance on having the _USE_MATH_DEFINES macro being defined
prior to any inclusion of cmath/math.h on Windows. This was easily
broken by bad include orders inside openvdb or by users of openvdb.

Sweep out use of M_PI* constants

---

openvdb/openvdb/version.h.in
pendingchanges/package_placeholder.txt

When distributing an OpenVDB package that is forked from the official it can be useful to provide the URL and commit hash that was used so people can re-create it or derive from it if they wish.
What we do for USD is have a define that we replace when we download the library from github with our particular URL and revision.  This seems like a useful thing to have in the master branch with the placeholder values, so others can follow a similar protocol if they wish.  If we eventually distribute binaries we may also ensure our binary build process likewise patches this.

Add a placeholder in version.h for the URL and revision to be stored

---

openvdb/openvdb/tools/Composite.h
openvdb/openvdb/tools/Merge.h
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Combine.cc

When the same tile subtracted from itself a background tile is created.
greatly reduces the generated ghost borders when similar objects are
differenced.
Provided for discussion.   Is a template parameter correct way for this?  I want this in VDB Combine as a toggle parameter, so do we also add parameters to higher level functions?  This also can extend to Union/Intersect.
And is this even a good thing?

Add a feature flag to the raw CsgDifferenceOp to immediately prune degenerate tiles.

---

cmake/FindBlosc.cmake
cmake/FindTBB.cmake
pendingchanges/build_fixes.txt

Fix for finding versioned TBB libraries as of TBB 2021.5 and Blosc external libs

---

.github/workflows/houdini.yml
.github/workflows/weekly.yml

@Idclip - this is a resubmission of #1458 but with one small change on top.
The issue here is the ABI test which works by building a single binary against libopenvdb.so and libopenvdb_sesi.so and attempting to create VDB grids in one library then pass them to the other and vice-versa to detect any ABI issues. This is less rigorous than the various ABI checker tools around, but is intended to replicate the exact situation that we run into if there's an ABI issue.
The libopenvdb.so library builds against libboost_iostream.so.1.73 which in turn builds against the system liblzma.so.5.2.2 (RHEL/CentOS 7).
The libopenvdb_sesi.so library builds against libhboost_iostreams.so.1.72 which in turn builds against liblzma.so.5.2.3 which is shipped in the dsolib directory of Houdini.
The problem is …

Enable Houdini CI

---

nanovdb/nanovdb/NanoVDB.h
nanovdb/nanovdb/PNanoVDB.h
pendingchanges/nanovdb.txt

Fixed a potential security vulnerability in NanoVDB.h related to buffer overflow exploits
sprintf is deprecated in C++17 since it's prone to buffer overflow, which is a serious security risk. This PR replaces sprintf in NanoVDB.h with snprintf which avoids buffer overflow by explicitly defining the maximum number characters written to the buffer.

replaced sprintf with snprintf to prevent future bufferoverflow

---

openvdb/openvdb/tools/PointIndexGrid.h

Fixes GCC 12 warning:
openvdb/tools/PointIndexGrid.h:1430:9: error: expected primary-expression before 'template'
1430 |         template BaseLeaf::merge<Policy>(rhs);
|         ^~~~~~~~

Remove a simple warning about missing template keyword

---

doc/changes.txt
openvdb/openvdb/points/AttributeArray.h
pendingchanges/removed_deprecated_virtual.txt

These methods have long been deprecated, but being virtual they have to be removed only on an ABI bump.

Remove deprecated virtual methods from AttributeArray for ABI=10

---

openvdb/openvdb/unittest/TestCount.cc
openvdb/openvdb/unittest/TestPointConversion.cc
openvdb/openvdb/unittest/TestPointCount.cc
openvdb/openvdb/unittest/TestPointRasterizeFrustum.cc

Fixes the extra lite weekly build which is building and evaluating the unit tests with delayed loading disabled.

Fix Unit Tests when Delayed Loading is Disabled

---

.github/workflows/docs.yml
openvdb/openvdb/tree/ValueAccessor.h
openvdb/openvdb/unittest/TestValueAccessor.cc
pendingchanges/accessors.txt

```
Improvements:
- Significantly improved the performance of all ValueAccessor methods which
access LeafNode value buffer data. This improvement applies to any type which
is delay load compatible (all default types except for bool and mask grids).
Bug Fixes:
- Fixed a bug with ValueAccessor::addLeaf which wouldn't add the provided
leaf nodes to the underlying tree. This bug did NOT affect the specialized
accessors which are used by the default tree configuration.
- Fixed a bug where ValueAccessor::probeNode<NodeT> and ValueAccessor:probeConstNode<NodeT>
would return a nullptr if the NodeT type was not explicitly being cached
by the accessor but the node existed in the tree.
```
Test 1 (Volume Advect)
Before: 1 minute, 35 seconds and 860.3 milliseconds (95860.3ms)
After: 1 minute, 28 …

ValueAccessor Buffer Cache

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Points_Convert.cc

... instead of the unsafe newDetachedPrimitiveGroup() that will be deprecated in a future Houdini version.

Use modern GA_Detail::createDetached*Group() API

---

openvdb/openvdb/tools/VolumeToMesh.h
pendingchanges/fixseampoint.txt

The pointflags in VolumeToMesh were unintialized if we took one of the computeCellPoints branches as we weren't testing the size of the weight array (as it had turned into a std::array)

Fix uninitialized pointflags

---

openvdb_ax/openvdb_ax/codegen/Types.h
pendingchanges/ax32fix.txt

IR void* is always i8* regardless

Fixed a build issue with AX on 32 bit platforms

---

nanovdb/nanovdb/NanoVDB.h

For reference:
```
openvdb/include/nanovdb/NanoVDB.h:1880:12: error: call to '__ffsll' is ambiguous
return __ffsll(v);
^~~~~~~
/opt/rocm-5.3.2/include/hip/amd_detail/amd_device_functions.h:69:39: note: candidate function
__device__ static inline unsigned int __ffsll(unsigned long long int input) {
^
/opt/rocm-5.3.2/include/hip/amd_detail/amd_device_functions.h:77:39: note: candidate function
__device__ static inline unsigned int __ffsll(long long int input) {
^
openvdb/include/nanovdb/NanoVDB.h:5567:61: warning: returning reference to local temporary object [-Wreturn-stack-address]
__hostdev__ const uint64_t& valueCount() const { return mGrid.valueCount(); }
^~~~~~~~~~~~~~~~~~
```

Fix NanoVDB build errors with HIP on Linux

---

openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc
openvdb_ax/openvdb_ax/test/integration/TestStandardFunctions.cc

An implementation is free to use any representation it likes for size_t. In general you'll have 32-bit size_t on 32-bit programs.
Fixes warning:
openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc: In instantiation of 'SeedType openvdb::v10_0::ax::codegen::{anonymous}::hashToSeed(size_t) [with SeedType = unsigned int; size_t = unsigned int]':
openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc:978:76:   required from here
openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc:56:19: warning: right shift count >= width of type [-Wshift-count-overflow]
56 |     } while (hash >>= sizeof(SeedType) * 8);
|              ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~

Prefer fixed-width integer types instead of size_t

---

nanovdb/nanovdb/util/GridStats.h

Remove the explicit default assignment operator - if this is specified, so should the copy constructor and move operators, as per rule of five.

Remove the explicit default assignment operator.

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Advect_Points.cc
pendingchanges/projectioncrash.txt

When I made the changes to switch from `GEOvdbProcessTypedGrid` to `GEOvdbApply`, I accidentally introduced this bug in the projection mode of the VDB Advect Points SOP:
https://github.com/AcademySoftwareFoundation/openvdb/pull/591/files#diff-3da92c28c566b6736ba31e46a2c8a84a00c8beada13f7c3cda90de1782014874R1022
This change fixes the bug so that this mode no longer crashes.
@jmlait

Fix Segfault in Projection Mode of VDB Advect Points SOP

---

openvdb/openvdb/tools/Composite.h
openvdb/openvdb/tools/Filter.h
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Combine.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Diagnostics.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_LOD.cc
pendingchanges/fix_int_in_bool_warnings.txt

The int-in-bool-context warnings are everywhere with GCC9, this PR uses lots of constexpr to try and fix them all.
One thing to note is that this also disables Bool Grids from being used in the VDB LOD SOP - I'm unsure if that's the correct thing to do, but seems to me that the prolong/restrict operations don't mean much in a bool context?

Fix all the int-in-bool-context warnings with GCC9

---

openvdb/openvdb/util/PagedArray.h
pendingchanges/pages_array_iterator.txt

Removed inheritance from std::iterator, deprecated from C++17

---

openvdb/openvdb/io/Archive.cc
openvdb/openvdb/io/Archive.h
pendingchanges/remove_boost_uuid.txt

This removes boost UUID from Archive, the member variable is changed to a std::string to match how we return the uniquetag to outside users.
We use std::random_device for all bits to ensure we have enough entropy.
The generated string isn't technically a UUID, but we never required it to be.  It should have its dashes in the correct place to load into old systems, however.

Remove Boost UUID

---

openvdb/openvdb/points/AttributeSet.h

I'm submitting this PR on behalf of a collegaue, C. Horvath. He reported a warning/error for VS2022:
`
C:\Users\chorvath\.conan\data\openvdb\10.0.0\blackencino\latest\package\f3f00aaf06c8145a4df169b78bec8a0b1e526438\include\openvdb\points\AttributeSet.h(41): warning #69-D: integer conversion resulted in truncation
`
Because in the absence of an integer base type the `enum` `INVALID_POS` defaults to an int, the truncation becomes a negative number. He proposed this solution. Another solution will be to make `INVALID_POS` to be a `static constexpr size_t`.

Addresses warning in vdb point: integer conversion resulted in truncation

---

nanovdb/nanovdb/unittest/TestNanoVDB.cc

Removes:
/<<PKGBUILDDIR>>/nanovdb/nanovdb/unittest/TestNanoVDB.cc:1729:16: warning: unsigned conversion from ‘long long int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘45634923663’ to ‘2685250703’ [-Woverflow]
1729 |       offset = 45634923663;
|                ^~~~~~~~~~~
/<<PKGBUILDDIR>>/nanovdb/nanovdb/unittest/TestNanoVDB.cc:1757:16: warning: unsigned conversion from ‘long long int’ to ‘size_t’ {aka ‘unsigned int’} changes value from ‘45634923663’ to ‘2685250703’ [-Woverflow]
1757 |       offset = 45634923663;
|                ^~~~~~~~~~~
/<<PKGBUILDDIR>>/nanovdb/nanovdb/unittest/TestNanoVDB.cc: In member function ‘virtual void TestNanoVDB_BasicGrid_Test::TestBody()’:
/<<PKGBUILDDIR>>/nanovdb/nanovdb/unittest/TestNanoVDB.cc:2286:39: warning: narrowing conversion of …

Use fixed-width integers to remove warnings (32bits)

---

nanovdb/nanovdb/NanoVDB.h
openvdb/openvdb/math/Coord.h

Hi!
I found that one of the constants used for hashing is not a prime number as claimed in the paper (19349663=41*471943). Note that this is also the case in the referred publication of [Teschner et al. [2003]](https://matthias-research.github.io/pages/publications/tetraederCollision.pdf).
I replaced it with the next closest prime number which is 19349669, which has been done [here](https://niessnerlab.org/papers/2013/4hashing/niessner2013hashing.pdf) as well.
Best
Benedikt

Fix prime number in voxel hashing

---

openvdb/openvdb/tools/LevelSetRebuild.h
openvdb/openvdb/tools/MeshToVolume.h
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_From_Polygons.cc
pendingchanges/hollowmesh.txt

From Tomas Skrivan comes this PR for providing hollow vdb support.
The volume-to-mesh gains an optional oracle to determine sign.   Rebuild level set uses this to ensure the rebuilt levelset always matches sign with the input.
From Polygons SOP gains an option to use the winding number to determine sign, enabled in H20 where the winding number is exposed.

Support for hollow VDBs

---

nanovdb/nanovdb/NanoVDB.h

This solves a compile error when using -Wmissing-braces.

Add missing braces

---

openvdb/openvdb/math/Half.h
pendingchanges/remove_half_lut.txt

OpenEXR 3 added an extern "C" LUT for Half.  The default configuration wasn't using it, but exporting it means that because the _type_ of the lookup table is namespaced, we can end up with conflicts if two namespaced versions of OpenVDB are compiled together, or OpenVDB with any OpenEXR external library.
This explicitly disables the creation of the Half LUT to avoid this.

Remove Half LUT

---

openvdb/openvdb/points/AttributeSet.cc

Fix C++20 compatibility by removing deprecated shared_ptr::unique()

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/weekly.yml
ci/install_macos.sh

- Fixed Houdini CI
- Fixed AX LLVM CI
- Added 2023 CI matrix
- Bumped the macos-latest jobs to use newer compilers to test C++20 features

CI updates

---

openvdb/openvdb/points/AttributeSet.cc
openvdb/openvdb/tools/Diagnostics.h
openvdb/openvdb/tools/GridTransformer.h
openvdb/openvdb/tools/LevelSetSphere.h
openvdb/openvdb/tools/ValueTransformer.h

- Fixed compatibility of OpenVDB and TBB by fixing invocations of `tbb::parallel_reduce`, which from C++20 have `__TBB_requires(tbb_range<Range> && parallel_reduce_body<Body, Range>)`. In that requires expression `parallel_reduce_body<Body, Range>` was failing because Body didn't have an `operator()` that takes a constant reference to `Range`:
```cpp
template <typename Body, typename Range>
concept parallel_reduce_body = splittable<Body> &&
requires( Body& body, const Range& range, Body& rhs ) {
body(range);
body.join(rhs);
};
```
- Replaced usage of `std::shared_ptr<T>::unique` (which was removed in C++20) by `std::shared_ptr<T>::use_count` (similiar to what @jdumas did in #1628 )
Fixes issue: #1590

Fixed C++20 compatibility of OpenVDB and TBB

---

CHANGES
doc/changes.txt
openvdb/openvdb/util/PagedArray.h

Get rid of `static_assert(std::random_access_iterator<PagedArray<int, 10UL>::ConstIterator>," ... ");` in `PagedArray.h`.

Make PagedArray to compile with clang14 with C++20 on the runner

---

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Convert.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Extrapolate.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Fracture.cc
openvdb_houdini/openvdb_houdini/SOP_OpenVDB_To_Polygons.cc

I'm not sure if we can actually hit these code paths in practice but this at least shuts up the warnings.

Fix nullptr dereferences found by gcc 11.4

---

openvdb_houdini/openvdb_houdini/GR_PrimVDBPoints.cc

Houdini 20 requires a RenderContext for this, which is functionally equivalent to Render *.  Include guard should provide 19.5 support as well.

Houdini 20 requires RenderContext rather than Render *.

---

.github/workflows/houdini.yml
.github/workflows/weekly.yml
README.md

Fix Houdini CI Caching

---

openvdb/openvdb/io/Archive.cc
openvdb/openvdb/io/io.h
openvdb/openvdb/points/PointDataGrid.h
openvdb/openvdb/tools/VelocityFields.h

Replace BOOST_STATIC_ASSERT with static_assert

Replace boost::any with std::any

---

openvdb/openvdb/math/Math.h

This appears to be a reasonable replacement for conversion_traits.  It appeared that sfinae was kicking in at a few places with the conversion type since a few functions were passing in non-arithmetic types (like mat3 and vec3) as scalars. The enable_if was added to fail the incorrect function templates before common_type is compiled.

Replace boost conversion_traits with std::common_type

---

openvdb/openvdb/CMakeLists.txt

Currently, when `USE_EXPLICIT_INSTANTIATION=ON`, re-running CMake will trigger recompilation of OpenVDB instantiation files. The culprit is the following line:
https://github.com/AcademySoftwareFoundation/openvdb/blob/3f8b6f30cf7c7d0d7f8fa7714965fb15d5db555b/openvdb/openvdb/CMakeLists.txt#L601
As the documentation for [file(WRITE)](https://cmake.org/cmake/help/latest/command/file.html#writing) mentions, one should use [configure_file()](https://cmake.org/cmake/help/latest/command/configure_file.html#command:configure_file) to copy generated files used as build sources, only if the content changes. Given that `USE_EXPLICIT_INSTANTIATION` was created to save time when recompiling dependent files, this is quite an unfortunate mistake. This PR fixes that.

Don't update timestamp when regenerating instantation files.

---

.github/workflows/nanovdb.yml

Fixing NanoVDB CI for VDB11 release:
- Updating CUDA to 11.6 on Linux.
- Fixing Windows NanoVDB CI.

Fix nanovdb CI and use the correct MSVC_RUNTIME library tag.

---

openvdb/openvdb/io/Compression.cc
pendingchanges/iofix.txt

Original fix thanks to Matthias Ueberheide.

Fix for potential crash when reading invalid .vdb files.

---

cmake/FindOpenVDB.cmake
doc/build.txt
doc/dependencies.txt
openvdb/openvdb/CMakeLists.txt
openvdb/openvdb/io/Compression.cc
openvdb/openvdb/math/Math.h
pendingchanges/iofix.txt

* Fix for potential crash when reading invalid .vdb files.
* Revert "Replace boost conversion_traits with std::common_type"
* Revert "Remove boost from the build system when OPENVDB_USE_DELAYED_LOADING is OFF"

Bug fixes to v11.0.0

---

openvdb/openvdb/math/Half.h

On some older CPUs without support for the lzcnt instruction, the conversion from half to float was wrong.
See AcademySoftwareFoundation/Imath#358 for more details.
Thanks to Ray Molenkamp for tracking down this bug.

Bump internal copy of half to fix issues on older x86_64 CPUs on Windows

---

openvdb/openvdb/python/pyGrid.h
openvdb/openvdb/python/pyOpenVDBModule.cc

1. Fixed `__setitem__` for iterators being bound to `getItem` instead of `setItem`
2. Removed obsolete class binding for PointDataIndex32 -- this is handled by the `PointDataIndex32` typecaster
3. Made the `TreeCombineOp` more concise and formally typed via the `std::functional` support in pybind11.

More pybind11 bugfixes and cleanup

---

nanovdb/nanovdb/util/CreateNanoGrid.h

Removing the validation warning in CreateNanoGrid::processGrid() to prevent the console from being spammed when a vector grid of type fog volume is processed. This change aim to match the behavior of before #1651.

Removing the validation warning in CreateNanoGrid::processGrid()

---

openvdb/openvdb/tree/LeafNode.h

Hi Academy Software Foundation! This merge request adds a small early-exit check to `LeafNode::resetBackground()`. This results in a significant speedup when an app merges grids on a node-by-node level using `Grid::merge(..., openvdb::MergePolicy::MERGE_NODES)`.
For a grid where voxels are either equal to the background value, or more than the default tolerance (1e-7) away from the (positive or negative) background value, `LeafNode::resetBackground()` is a no-op if `oldBackground == newBackground` or `oldBackground == -newBackground`:
```cpp
template<typename T, Index Log2Dim>
inline void
LeafNode<T, Log2Dim>::resetBackground(const ValueType& oldBackground,
const ValueType& newBackground)
{
if (!this->allocate()) return;
typename NodeMaskType::OffIterator iter;
// For all inactive …
```

Add early-exit optimization for LeafNode::resetBackground()

---

ci/download_houdini.py
cmake/OpenVDBHoudiniSetup.cmake
openvdb/openvdb/math/Mat4.h

- Fixed an incorrect assert in Mat4.h. This should fix the debug CI.
- Fixed an issues caused by 6ce7033a2ba1a641c8ba1a32d22cc25afcd4473a (basically we want to prefer jemalloc, but don't use the one shipped by Houdini on MacOS). This should fix the Houdini CI stalling.

Various Fixes

---

nanovdb/nanovdb/NanoVDB.h

guarding UINT64_C in nanovdb (for NVRTC users who have it defined already)

guarding UINT64_C in nanovdb

---

RE-LICENSE_NOTE.txt

DreamWorks Animation and NBCU legal teams have reviewed and approved the request to relicense DWA contributions to OpenVDB from MPL-2.0 to Apache-2.0.
Per guidance from the OpenVDB TSC, we are adding DreamWorks Animation to `RE-LCENSE_NOTE.txt` to mark our approval.

Add DWA to Apache 2.0 RE-LICENSE_NOTE.txt

---

tsc/meetings/2024-04-30.md

Add TSC meeting notes from April 30, 2024. Topics:
- You can use `pip` install for NanoBind, making it easier to support NanoBind dependency.,
- fVDB presentation. fVDB is a framework for doing spatial reasoning with sparse volumetric 3D data structure. It includes deep learning framework, such as sparse convolution operators.

Add TSC meeting notes from April 30, 2024.

---

openvdb/openvdb/math/Vec3.h

We are adding `cwiseAdd` template specialization on `half` type for `Vec3` class. This is to address the issue encountered in [PR-1723](https://github.com/AcademySoftwareFoundation/openvdb/pull/1723).

Bug fix: the half type doesn't satisfy std::is_arithmetic so the operator doesn't get instantiated

---

CONTRIBUTING.md
MAINTAINERS.md
tsc/process/codereview.md

Ensure all TSC are Maintainers
Add Jonathan Swartz as a Maintainer.
Adjust voting procedure for new TSC members to require TSC approval, not maintainer approval.

Rename Committer to Maintainer

---

openvdb/openvdb/Types.h
openvdb/openvdb/math/Vec3.h

Template specialization of `cwiseAdd` for `Vec3` half-type should be in be in `Types.h` instead of in `math/Vec3.h`.

Fixing build issue caused by adding cwiseAdd in `math/Vec3.h`

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/docs.yml
.github/workflows/houdini.yml
.github/workflows/nanovdb.yml
.github/workflows/weekly.yml
ci/install_windows_cuda.ps1

Fix NanoVDB CI: `NanoVDB` lite and on Windows: upgrade to CUDA 12.4 for Visual Studio 2022, allow use of unsecure node version, use node 16 in ax, build, docs, houdini, and weekly workflow.

More CI Fixes

---

.github/workflows/weekly.yml

I'm going to merge this one change and kick off a weekly build manually, as I cannot test this PR (https://github.com/AcademySoftwareFoundation/openvdb/pull/1898) when the updated cache only lives on a feature branch.

Use Apple Silicon Houdini Downloads

---

nanovdb/nanovdb/unittest/TestNanoVDB.cu

This fixes an issue building the NanoVDB unit tests on Windows due to these errors:
```
unittest\TestNanoVDB.cu(2555): error : namespace "std" has no member "setw" 
unittest\TestNanoVDB.cu(2555): error : namespace "std" has no member "setfill" 
```
(@kmuseth @apradhana)

Fix NanoVDB Build

---

.github/workflows/build.yml
.github/workflows/nanovdb.yml
.github/workflows/weekly.yml

As we recently discussed, this moves all debug and static windows builds to the weekly CI instead of running on every PR. This leaves just the CI for the shared library release build for OpenVDB and for NanoVDB. A potential next step is to consolidate these two builds under a single CI job as we are still seeing long times for installing all of the Windows dependencies (when we are not making use of the wider machines). It is always possible to manually kick off a weekly CI run when making substantial changes or build system changes.
This is intended to significantly reduce our use of ASWF CI budget as Windows is the most expensive CI and is our longest running.

Move all debug and static windows builds to the weekly CI

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/houdini.yml
.github/workflows/nanovdb.yml

Ensure changes to fvdb sub-project don't trigger other project CI workflows

fVDB CI paths-ignore

---

ci/install_windows.sh

All our Windows CI checks are failing right now due to an issue with vcpkg + bash + github actions. This suggested work-around resolve this. In making this change, I also noticed a couple of small bugs with the fallback vcpkg workflow that wasn't correctly aborting when the installation failed.

Fix a couple of small windows CI / vcpkg bugs

---

.github/workflows/weekly.yml

This addresses a small issue in the latest build by explicitly setting the LLVM directory path. I also disabled axtest because a few unit tests were failing with LLVM 15, this needs more investigation.

Fix Weekly CI Latest Builds

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/houdini.yml
.github/workflows/nanovdb.yml
.github/workflows/weekly.yml
ci/install_cppunit.sh
ci/install_glfw.sh

This drops CI jobs for the VFX Reference Platform 2021 images which we are about to drop support for and introduces 2024 images which we haven't used until now. I've also removed the clang-specific images in favor of the base image (where possible, AX does not yet work on LLVM>15). There was an outstanding issue where the version of glfw was incorrectly installed in the 2023 image so this is now installed from source to resolve this.

Add 2024 CI Images and Drop 2021 CI Images

---

fvdb/notebooks/01_api_basics.ipynb

Fixed a minor typo causing minor confusion in one of the tutorial notebooks.

fVDB: Fix typo in 01_api_basics.ipynb

---

CMakeLists.txt
ci/install_nanobind.sh
cmake/FindOpenVDB.cmake

Fixing a few python-related issues that was failing the weekly CI. Remove some Python2 functionality from CMake build (no longer required now that OpenVDB is Python 3+) and adding a "site-packages" fallback if `Python_SITELIB` is not defined. Finally, fixes an issue where nanobind needs to be installed using sudo on ubuntu.
@matthewdcong

Python CI Fixes

---

openvdb/openvdb/tree/RootNode.h
pendingchanges/root_node_emplace.txt

A couple of small optimizations and slightly improved readability, no changes in behavior. This refactors this pattern:
```
MapIter iter = this->findCoord(xyz);
if (iter == mTable.end()) {
auto* child = new ChildT(xyz, ...);
mTable[this->coordToKey(xyz)] = NodeStruct(*child);
```
into:
```
Coord key = this->coordToKey(xyz);
MapIter iter = this->findKey(key);
if (iter == mTable.end()) {
auto* child = new ChildT(xyz, ...);
mTable.emplace(key, *child);
```
It avoids performing the coord->key conversion twice and uses emplace for in-place creation of the NodeStruct object.

Root Node Optimizations

---

openvdb/openvdb/tree/InternalNode.h
openvdb/openvdb/tree/RootNode.h
openvdb/openvdb/unittest/TestInternalNode.cc
openvdb/openvdb/unittest/TestRootNode.cc
pendingchanges/probe.txt

This PR adds a bunch of new "probe" methods to fill in some gaps in the API in being able to query child nodes as well as adds some additional convenience methods. 
**RootNode**
The root node adds convenience methods to query the child nodes (as opposed to needing to supply a template parameter `probeNode<ChildT>(const Coord&)`). In addition, there are new `probe()` methods that query whether a key exists (and returns false if not) and returns either a child node or a value and active state otherwise. Finally, a templated `probeNode()` method that can be called on a const RootNode has been added.
Here are all the new RootNode methods:
```
ChildNodeType*       RootNode::probeChild(const Coord&);
const ChildNodeType* RootNode::probeConstChild(const Coord&) const;
const ChildNodeType* …
```

RootNode and InternalNode Probe Methods

---

openvdb/openvdb/tools/ValueTransformer.h
openvdb/openvdb/unittest/TestTools.cc

This is failing the ubsan checks in Clang 17.

Disable undefined behavior checks in transformValues()

---

openvdb/openvdb/tools/LevelSetFilter.h
openvdb/openvdb/unittest/CMakeLists.txt
openvdb/openvdb/unittest/TestLevelSetFilter.cc
pendingchanges/levelset_fillet.txt

Added a unit test for the `fillet()` method in `tools::LevelSetFilter` contributed by @ghurstunither .

Add a unit-test for LevelSetFilter::fillet.

---

openvdb/openvdb/tree/RootNode.h

The address sanitizer CI picked up that there was a memory leak in the `RootNode::deleteChildOrTile()` method and I realize that the NodeStruct doesn't delete the child on destruction so I've fixed this by explicitly deleting it.
I also added a warning that this method will invalidate existing iterators as previously requested.
(@kmuseth)

Fix a memory-leak in RootNode::deleteChildOrTile()

---

ci/install_windows.ps1

The Windows static builds are failing when using vcpkg and attempting to install pdal. Removing pdal, which is unused as far as I can tell in the CI currently.
(@swahtz)

Fix Windows CI

---

nanovdb/nanovdb/tools/GridBuilder.h
openvdb/openvdb/tree/NodeManager.h

Upcoming versions of Clang/LLVM change some behaviour around templating that causes OpenVDB to fail to compile.
This commit addresses two issues and allows VDB to compile again.
1. There were three instances of an unnecessary template keyword in NodeManager.h that were not followed by a template call, and therefore are illegal to the compiler.
2. GridBuilder.h had a template call to a non-existent method. This was not previously validated, but is now validated.  Switching the call from `isActive` to `isOn` works (as suggested by Ken).
See the [changelog](https://releases.llvm.org/19.1.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics:~:text=Clang%20now%20looks%20up%20members%20of%20the%20current%20instantiation%20in%20the%20template%20definition%20context%20if%20the% …

Fix Clang Template errors

---

nanovdb/nanovdb/tools/NanoToOpenVDB.h
pendingchanges/nanovdb_transpose.txt

The openvdb::Mat3::transpose() method returns a transpose of itself, it doesn't do an in-place transpose.
Thus the line
mat.transpose(); // the 3x3 in nanovdb is transposed relative to openvdb's 3x3
is a no-op, and not actually transposing the matrix.  Since we DO transpose when we do an OpenToNano; it is important we transpose here or we can't round-trip.
Unfortunately, it has been this way since the initial commit, so it is quite likely tooling has already worked around this....

Transpose on NanoToOpenVDB allowing round tripping

---

.github/workflows/ax.yml
.github/workflows/build.yml
.github/workflows/houdini.yml
.github/workflows/nanovdb.yml
.github/workflows/weekly.yml

The ASWF Ubuntu 20.04 runners were deprecated and have since been removed which means Linux CI jobs are now queuing indefinitely and failing. This PR upgrades from the Ubuntu 20.04 runners to the more recent Ubuntu 22.04 runners.

Upgrade from deprecated/since removed Ubuntu 20.04 runners

---

openvdb/openvdb/io/Archive.cc

We are reading very large openvdb volumes (8gb and larger) and discovered that, on our Windows systems, using `delayLoad=true` for volumes causes 10x slower file reads compared to `delayLoad=false`.
Profiling pointed us to this behavior in `Archive::getLastWriteTime()`, which makes three system calls (open file, get file time, close file): https://github.com/AcademySoftwareFoundation/openvdb/blob/5ff0edc2cc333a70923c0122d6a6deec3bc80cc4/openvdb/openvdb/io/Archive.cc#L506-L512
The above is called once per node when reading the node from the file due to this check in `MappedFile::createBuffer()`: https://github.com/AcademySoftwareFoundation/openvdb/blob/5ff0edc2cc333a70923c0122d6a6deec3bc80cc4/openvdb/openvdb/io/Archive.cc#L557-L565
This check and warning is unnecessary on Windows as memory …

Slowdown fix - Avoid unnecessary getLastWriteTime calls for memory mapped files on windows

---

openvdb/openvdb/io/Compression.h
openvdb/openvdb/points/PointDataGrid.h
pendingchanges/write_compressed_const.txt

It is not currently possible to pass in a `const ValueT*` to `io::writeCompressedValues()` because it requires the array to be non-const (even though it is not actually modified).
A small refactoring here allows us to improve const-correctness.

Improve const-correctness in io::writeCompressedValues
