openvdb/Makefile, openvdb/tree/LeafBuffer.h, openvdb/tree/LeafNode.h, openvdb/tree/LeafNodeBool.h, openvdb/tree/LeafNodeMask.h
=> Extract LeafNode<>::Buffer into a separate LeafBuffer class

BuildingWithCMake.md
Example script to build OpenVDB's Maya node using TBB that is package with Maya (via MAYA_LOCATION)
=> Maya node build instructions

openvdb/Makefile, openvdb/doc/doc.txt, openvdb/doc/examplecode.txt, openvdb/doc/points.txt, openvdb/doxygen-config
Introducing a Doxygen page to document OpenVDB Points and some code examples.
=> OpenVDB Points Documentation and Code Examples

openvdb/points/PointDataGrid.h
These are otherwise stored in the stream auxiliary data and will result in the stream metadata created in Archive::doReadGrid() to not be cleaned up after restoring the file-level stream metadata. The result is that the mapped file used in delayed-loading a PointDataGrid will not be released in specific situations, leading to increasing memory consumption.
=> Fix delay-loading memory leak on read by correctly clearing paged stream pointers

openvdb/cmd/openvdb_view/main.cc, openvdb/viewer/RenderModules.cc, openvdb/viewer/RenderModules.h, openvdb/viewer/Viewer.cc
Added support for displaying points from PointDataGrids with vdb_view
=> Added point view to vdb_view

openvdb/points/AttributeArray.h
Resolve issues with double-checked locks when attempting to access the same delay-loaded PointDataLeafNodes from multiple threads concurrently (typically seen in a rendering context).
This implementation deprecates the out-of-core flag on AttributeArrays in favour of using a sequentially-consistent atomic and matches the same fix introduced to the LeafNode.
This changes ABI, so is conditionally introduced for ABI=5 only.
=> Use an atomic for out-of-core arrays to prevent double-checked lock issues

openvdb_houdini/houdini/PointUtils.cc
Merge error, accidentally picked up a couple of inline statements.
=> Fix linking bug in openvdb houdini

openvdb/points/PointDataGrid.h, openvdb/unittest/TestPointDataLeaf.cc
Small extension to the API to be able to prefetch just the voxel data and just the position attribute.
=> Minor improvements to prefetching

cmake/FindTBB.cmake
Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>
=> Fix typo: handle

.travis.yml, travis/travis.py, travis/travis.run
* Update http => https link
* Fix Change in SideFX download URLs
* Deprecate H15.0 and H15.5 builds
=> Fix Travis Houdini

CONTRIBUTING.md
=> Added stub CONTRIBUTING file.

openvdb/points/AttributeArray.h, openvdb/unittest/TestAttributeArray.cc
Signed-off-by: Peter Cucka <peter.cucka@dreamworks.com >
=> Fixes for various AttributeArray-related compiler and Doxygen warnings

tsc/meetings/2018-11-30.md, tsc/meetings/2018-12-06.md
=> Last two TSC meeting notes.

openvdb_houdini/houdini/SOP_OpenVDB_Advect_Points.cc
Introduced a new primitive group field that applies to just VDB points primitives.
@jmlait - I've layered a commit on top of your previous commit (rather than appending to your https://github.com/AcademySoftwareFoundation/openvdb/pull/278). I tried a few different approaches to solve the filtering issue here, this seemed the best option to me. There are now two native filtering fields - a points one for Houdini points and a primitive one for VDB points. In addition there is a VDB points group field too. Although this does slightly confuse the UI having three filtering fields, I've tried to name and arrange the options so that it's as clear as possible. Obviously the main goal here is that the user can feed in any data, points or VDB points and by default (no filtering) everything will get …
=> Advect Points can advect *both* VDB points and points

openvdb/CHANGES, openvdb/Makefile, openvdb/doc/changes.txt, openvdb/python/CMakeLists.txt, openvdb/python/pyGrid.h, openvdb/python/pyOpenVDBModule.cc, openvdb/python/pyPointGrid.cc, openvdb/python/pyutil.h, openvdb/python/test/TestOpenVDB.py, travis/travis.run
A re-submission of https://github.com/AcademySoftwareFoundation/openvdb/pull/213.
=> Add PointDataGrid support to Python bindings

openvdb/tools/ValueTransformer.h
Resubmission of PR #199 with proper DCO.
=> Add += support for bools in SumOp.

tsc/meetings/2019-01-24.md
TSC Meeting minutes for 2019-01-24.
=> TSC Meeting minutes for 2019-01-24.

tsc/process/release.md
=> Release process documentation

openvdb/unittest/TestAttributeArray.cc
=> Ensure deletion of temporary file in TestAttributeArray

openvdb/unittest/TestAttributeArray.cc, openvdb/unittest/TestCoord.cc, openvdb_houdini/houdini/SOP_OpenVDB_Fill.cc, openvdb_houdini/houdini/SOP_OpenVDB_Points_Convert.cc
Warnings when using strict compile mode.
=> Fix some strict warnings

openvdb/python/test/TestOpenVDB.py
=> Removed some obsolete, DWA-specific logic from TestOpenVDB.py

openvdb_houdini/houdini/GEO_PrimVDB.cc, openvdb_houdini/houdini/GEO_PrimVDB.h
Improved topology merging.  Expansion to bool grids for topology
operations.
Note that there are no longer non-AMD64 platforms, and that is placeholder
for 32bit.  So the atomic counter is effectively 64bit.`
=> Synchronize with Houdini 17.5's version.

tsc/meetings/2019-02-14.md
=> Meeting notes Feb 14th

openvdb/CHANGES, openvdb/doc/changes.txt, openvdb/python/pyOpenVDBModule.cc, openvdb/python/test/TestOpenVDB.py
=> OVDB-51: Add support for Mat4s and Mat4d metadata to pyopenvdb.

openvdb_houdini/houdini/SOP_OpenVDB_Points_Delete.cc
Limit the scope of the acquired const grid pointers.  This will 
cause the grid to not be unique, and trigger asserts as the meta
data is unexpectedly shared.
=> Limit the scope of the acquired const grid pointers.  

tsc/meetings/2019-02-28.md
Meeting notes for Feb 28th, 2019.
=> Meeting notes for Feb 28th, 2019.

openvdb/cmd/openvdb_lod.cc, openvdb/python/pyOpenVDBModule.cc, openvdb/unittest/TestTreeCombine.cc
=> Minor fixes for misc. compiler warnings

tsc/meetings/2019-03-07.md
Feel free to suggest edits, especially as I moved rooms during the call. :)
Signed-off-by: Dan Bailey <danbailey@ilm.com>
=> Adding meeting notes for 10th meeting.

CONTRIBUTING.md
As per meeting notes of Jan 17, reword the 25% requirement.
=> As per meeting notes of Jan 17, reword the 25% requirement.

tsc/meetings/2019-03-21.md
=> TSC Meeting Notes for March 21st 2019.

openvdb/tools/MeshToVolume.h
The test every spawntask was not aggressive enough for some case (SideFX Bug: 95926), so add a gated test in rasterize functions as well.
=> Improve interruptability of the MeshToVolume

tsc/meetings/2019-04-18.md
TSC Meeting notes for April 18th, 2019.
=> TSC Meeting notes for April 18th, 2019.

openvdb/CHANGES, openvdb/doc/changes.txt, openvdb/points/AttributeArray.cc, openvdb/points/AttributeArray.h, openvdb/unittest/TestAttributeArray.cc
=> Fix for OpenVDB Points strided attribute serialization

tsc/meetings/2019-04-25.md
TSC Meeting Notes for April 25th, 2019.
=> TSC Meeting Notes for April 25th, 2019.

tsc/meetings/2019-05-02.md
=> TSC Meeting Notes for May 2nd, 2019.

README.md
=> Link build documentation on readme

openvdb/CHANGES, openvdb/doc/changes.txt, openvdb/tools/PotentialFlow.h
https://www.openvdb.org/forum/?place=msg%2Fopenvdb-forum%2FrD5B3SXORdw%2FWcqynrP9AgAJ
=> Minor bugfix for SolveBoundaryOp operator in PotentialFlow.h

openvdb/CHANGES, openvdb/doc/changes.txt
=> Updated release notes

azure-pipelines.yml
Add a basic hello world azure pipelines yml to the repo. We can use this as the basis to setup the CI infrastructure, GitHub checks, etc before looking to merge #449.
(I want to avoid the migration issues that we had with Circle).
=> Azure Hello World

tsc/meetings/2019-05-23.md
=> TSC minutes

tsc/meetings/2019-05-30.md
TSC Meeting Notes May 30th, 2019
=> TSC Meeting Notes May 30th, 2019

openvdb/version.h
=> Fixed missing bracket in version.h

tsc/meetings/2019-06-13.md
=> TSC Minutes 13th June

openvdb/INSTALL, openvdb/doxygen-config, openvdb/version.h
=> Bump library version number from 6.1.1 to 6.2.0

openvdb/CHANGES, openvdb/doc/changes.txt, openvdb/unittest/TestUtil.cc, openvdb/util/PagedArray.h
Fixed a bug in util::PagedArray caused by a race condition (due to an incorrect template argument)
=> Bug fix paged array

tsc/meetings/2019-06-20.md
=> TSC Notes June 20th, 2019

tsc/process/security.md
=> Security Policy.

CHANGES, doc/changes.txt, openvdb/CMakeLists.txt, openvdb/Makefile, openvdb/tools/FindActiveValues.h, openvdb/unittest/TestFindActiveValues.cc
@kmuseth - some stuff I missed on review. Mostly minor edits, a few typos, CMake is the main build system, but we should still keep supporting Makefiles for the time being - hopefully we can deprecate this soon.
=> FindActiveValues - Minor build system, release notes and typo fixes

LICENSE, README.md, doc/faq.txt
This PR adds the text of the MPL-2.0 license to the LICENSE file. 
It also clarifies the descriptions of the project's license in a couple
of documentation files.
Signed-off-by: Steve Winslow <swinslow@gmail.com>
=> Added MPL-2.0 text and clarified license descriptions

tsc/meetings/2019-08-22.md
=> TSC meeting notes August 22nd

tsc/meetings/2019-08-29.md
=> TSC Meeting notes August 29th, 2019

CHANGES, doc/changes.txt, openvdb/unittest/CMakeLists.txt
=> Added missing unit test TestClip

CHANGES, doc/changes.txt, doc/examplecode.txt, doc/faq.txt
- Updated the FAQ with a better discussion of ABI compatibility.
- Removed outdated build documentation from the Cookbook.
- Made various minor formatting and style changes.
=> Misc. minor documentation tweaks

azure-pipelines.yml
* Migrate from aswftesting -> aswf docker containers
* Use vfx2020 as the main image 
* Drop Houdini 16.5 build
=> Update Docker Containers for CI

tsc/meetings/2019-09-26.md
=> Minutes from 28th OpenVDB TSC meeting, September 26th, 2019, (GMT)

tsc/meetings/2019-10-10.md
=> TSC Notes for October 10th

openvdb_houdini/GU_PrimVDB.cc
Do not try to make metadata out of non-tuples as we don't support them
=> Do not try to make metadata out of non-tuples as we don't support them

openvdb_houdini/SOP_OpenVDB_Read.cc
=> Include cctype.h which is required for isdigit.

tsc/meetings/2019-11-14.md
TSC Meeting November 14th 2019
=> TSC Meeting November 14th 2019

openvdb/math/Math.h, openvdb/tools/LevelSetAdvect.h, openvdb/tools/Morphology.h, openvdb/util/NodeMasks.h
=> Allow magic statics as they have been supported as of Visual Studio 2015

tsc/meetings/2019-10-31.md
=> TSC meeting notes 2019-10-31

LICENSE, README.md
Signed-off-by: Jeff Bradley <jeff.bradley@dreamworks.com>
=> Simplify license text

CHANGES, CMakeLists.txt, doc/changes.txt, openvdb/Platform.h, openvdb/Types.h, openvdb/python/pyGrid.h, openvdb/version.h
=> Various Visual Studio 2017 Improvements

tsc/meetings/2019-11-14.md, tsc/meetings/2019-11-21.md
(I also fixed the date on the last meeting notes that I missed when reviewing).
=> Meeting notes 21st November 2019

CHANGES, doc/changes.txt, openvdb/tools/MeshToVolume.h
See the ticket for more information https://jira.aswf.io/browse/OVDB-117
=> [OVDB-117] Mesh To Volume bugfix

tsc/meetings/2019-11-28.md
TSC meeting notes November 28th.
=> TSC meeting notes November 28th.

openvdb/tree/Tree.h, openvdb/unittest/TestGrid.cc, openvdb/unittest/TestTree.cc
=> fixed bugs

CHANGES, doc/changes.txt
=> [OVDB-132] Release 7.0.0

CHANGES, doc/doxygen-config, openvdb/version.h
=> Start Version 7.0.1

tsc/meetings/2019-12-05.md
=> TSC Minutes 5 December

openvdb/math/Stencils.h, openvdb_houdini/SOP_OpenVDB_Visualize.cc
Fixes to compile in MSVC 2019.
=> Send upstream msvc 2019

tsc/meetings/2020-01-09.md
=> Meeting Notes.

cmake/OpenVDBHoudiniSetup.cmake, openvdb_houdini/CMakeLists.txt
=> Fixes to cmake/OpenVDBHoudiniSetup.cmake for Windows builds

tsc/meetings/2020-01-16.md
=> TSC Notes 16th Jan

CHANGES, doc/changes.txt, openvdb/math/Transform.h, openvdb/points/PointDataGrid.h, openvdb/points/PointMove.h, openvdb/tree/InternalNode.h, openvdb/tree/LeafNode.h, openvdb/tree/LeafNodeBool.h, openvdb/tree/LeafNodeMask.h, openvdb/tree/RootNode.h, openvdb/viewer/RenderModules.cc, openvdb_maya/OpenVDBUtil.h
MSVC 19.10 is now our minimum.
=> OVDB-131: Remove more MSVC special case code

tsc/meetings/2020-01-23.md
=> Notes for TSC : 0123 meeting.

openvdb_houdini/CMakeLists.txt, openvdb_houdini/GEO_PrimVDB.cc, openvdb_houdini/GEO_PrimVDB.h, openvdb_houdini/GU_PrimVDB.cc, openvdb_houdini/GU_PrimVDB.h
=> Fixes to the Houdini source files bundled with OpenVDB

doc/build.txt, doc/dependencies.txt
=> Minor documentation fixes

CHANGES, cmake/OpenVDBGLFW3Setup.cmake, doc/changes.txt
=> Fix GLFW CMake warning

tsc/meetings/2020-02-20.md
=> TSC Meeting notes for Feb 20.

openvdb/tools/Filter.h
=> Fix box filter function name (Filter::doBoxY/doBoxZ)

tsc/meetings/2020-03-05.md
=> TSC Meeting Notes 5th March

openvdb/unittest/TestDenseSparseTools.cc, openvdb_houdini/ParmFactory.cc, openvdb_houdini/SOP_OpenVDB_Rasterize_Points.cc
Removed checks according to cpp guidelines linked in the original post.
=> Remove unnecessary null pointer checks #257

tsc/meetings/2020-04-02.md
TSC meeting notes for April 2nd 2020.
=> TSC meeting notes for April 2nd 2020.

tsc/meetings/2020-04-09.md
=> TSC minutes, 9th April

.github/workflows/build.yml, ci/build.sh, ci/build_windows.sh, ci/install_macos.sh
=> Added a basic MacOS CI build and test

tsc/meetings/2020-04-30.md
=> TSC Notes for April 30th, 2020.

openvdb_houdini/CMakeLists.txt, openvdb_houdini/Makefile, openvdb_houdini/SOP_OpenVDB_Activate.cc
Initial attempt to move the code over and see how it compiles and what people think of the partial-completion of code-style.
=> Initial attempt to move Houdini's VDB Activate into OpenVDB.

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/whitespace.yml, ci/build_docs.sh, ci/install_doxygen.sh, ci/install_houdini.sh, ci/install_houdini_azure.sh, doc/changes.txt, doc/points.txt, openvdb_houdini/GEO_PrimVDB.cc, openvdb_houdini/GEO_PrimVDB.h, openvdb_maya/AEOpenVDBCopyTemplate.mel, openvdb_maya/AEOpenVDBFilterTemplate.mel, openvdb_maya/AEOpenVDBFromMayaFluidTemplate.mel, openvdb_maya/AEOpenVDBFromPolygonsTemplate.mel, openvdb_maya/AEOpenVDBTransformTemplate.mel, openvdb_maya/AEOpenVDBVisualizeTemplate.mel, openvdb_maya/AEOpenVDBWriteTemplate.mel
* Add whitespace CI check (and fix some whitespace issues)
* Add docs CI check (and fix some doxygen issues)
* Adjust rules for build workflow to only build on specific files
=> GitHub Actions CI for Docs and Whitespace

tsc/meetings/2020-05-21.md
=> Latest meeting notes.

.github/workflows/build.yml, CHANGES, ci/build.sh, ci/test_install.sh, cmake/FindOpenVDB.cmake, doc/changes.txt
=> Updated FindOpenVDB to support pyopenvdb and openvdb_houdini

openvdb/cmd/openvdb_lod.cc
Seeing this come up more and more in open source projects, it would be good to be cognizant of terms used. Good discussion in another community at https://github.com/rails/rails/issues/33677
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>
=> Change from white list to accept list

openvdb_houdini/GEO_VDBTranslator.cc, openvdb_houdini/SOP_OpenVDB_Scatter.cc, openvdb_houdini/SOP_VDBVerbUtils.h
Signed-off-by: Edward Lam <edward@sidefx.com>
=> Modernize to use override to avoid gcc's -Wsuggest-override warning

tsc/meetings/2020-06-04.md
=> TSC Minutes June 4th

tsc/meetings/2020-06-18.md
=> Meeting notes for June 18th.

tsc/meetings/2020-06-30.md
=> TSC 30th June Minutes

CHANGES, CMakeLists.txt, cmake/FindOpenVDB.cmake, doc/changes.txt, openvdb/CMakeLists.txt, openvdb/cmd/CMakeLists.txt, openvdb/unittest/CMakeLists.txt
=> Disable jemalloc by default and allow for downstream jemalloc targets

tsc/meetings/2020-07-07.md
=> TSC Notes July 7th

CHANGES, doc/changes.txt, openvdb_houdini/SOP_OpenVDB_From_Particles.cc, openvdb_houdini/SOP_OpenVDB_From_Polygons.cc
Added "v" and "point.v" as first option to the drop-down with a separator. Any others we should include here?
=> Remove PRM_CHOICELIST_EXCLUSIVE from VDB from Polygons/Particles

.github/workflows/houdini.yml
Once we have a successful Houdini install in the cache, I'll update the CI jobs for 17.5.
=> Add Houdini 17.5 to weekly build and update schedule day to Sunday

tsc/meetings/2020-07-21.md
=> TSC Minutes 07/21

tsc/meetings/2020-07-28.md
=> TSC notes for July 28th.

CHANGES, CMakeLists.txt, cmake/FindBlosc.cmake, doc/changes.txt, openvdb/CMakeLists.txt, openvdb/tools/FastSweeping.h, openvdb/unittest/TestFastSweeping.cc
=> New branch with final version of FastSweeping

tsc/meetings/2020-08-04.md
=> TSC 4th Aug

CHANGES, doc/changes.txt, openvdb_houdini/SOP_OpenVDB_Points_Convert.cc
- Fixed a bug where the auto voxel transform was being calculated on the packed geometry in the OpenVDB Points Convert SOP
- Fixed a bug where points representing packed geometry were also being converted in the OpenVDB Points Convert SOP
=> OpenVDB Points Convert SOP Fixes

openvdb_houdini/GEO_PrimVDB.cc, openvdb_houdini/GEO_PrimVDB.h, openvdb_houdini/GU_PrimVDB.cc, openvdb_houdini/GU_PrimVDB.h
Main changes
- More meta attribute support
- use overrides
- Fix bug with empty grids early-terminating the enlargeBoundingBox.
Note this is just a reference implementation.
=> Synchrnoize with 18.5.  

nanovdb/Readme.md
Please accept - this is just a test
=> test commit

.github/workflows/whitespace.yml, nanovdb/Readme.md
=> test commit #2

.github/workflows/houdini.yml
=> Bump the hou17.5 cron build to install cmake 3.12

tsc/meetings/2020-08-18.md
=> TSC Meeting Notes

openvdb/openvdb/tools/FastSweeping.h, openvdb/openvdb/unittest/CMakeLists.txt
Unit test was missing from CMakeLists.txt and assert is not correct so remove it.
(@apradhana)
=> Add fast sweeping unit test and remove incorrect assert

tsc/meetings/2020-09-22.md
=> Meeting notes for 2020-09-22.

nanovdb/.circleci/config.yml, nanovdb/CMakeLists.txt, nanovdb/Makefile, nanovdb/cmd/CMakeLists.txt, nanovdb/cmd/convert/nanovdb_convert.cpp, nanovdb/cmd/print/nanovdb_print.cpp, nanovdb/cmd/validate/nanovdb_validate.cpp, nanovdb/docs/FAQ.md, nanovdb/examples/benchmark/Benchmark.cpp, nanovdb/examples/ex_bump_pool_buffer/bump_pool_buffer.cpp, nanovdb/examples/ex_map_pool_buffer/map_pool_buffer.cpp, nanovdb/nanovdb/NanoVDB.h, nanovdb/nanovdb/util/GridBuilder.h, nanovdb/nanovdb/util/GridChecksum.h, nanovdb/nanovdb/util/GridStats.h, nanovdb/nanovdb/util/IO.h, nanovdb/nanovdb/util/OpenToNanoVDB.h, nanovdb/nanovdb/util/SampleFromVoxels.h, nanovdb/unittest/TestNanoVDB.cpp, nanovdb/unittest/TestOpenVDB.cpp
Another major revision of NanoVDB (note that old .nvdb files will have to be re-generated!)
=> another major revision of NanoVDB

CHANGES, doc/changes.txt, openvdb/openvdb/unittest/TestUtil.cc, openvdb/openvdb/util/PagedArray.h
Fixed crash in unittest of PagedArray
=> Fixed crash in PagedArray unit test

tsc/meetings/2020-10-27.md
=> Meeting notes for Oct 27th.

CHANGES, doc/changes.txt, openvdb/openvdb/tools/LevelSetUtil.h
=> Fixed undefined behaviour with empty vector accesses

.github/workflows/build.yml, cmake/FindBlosc.cmake
https://github.com/AcademySoftwareFoundation/openvdb/actions/runs/369706411
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Fix Windows actions CI

.github/workflows/houdini_cache_update.yml, ci/build_houdini.sh
=> Minor fix to houdini CI

tsc/meetings/2020-11-17.md
=> Meeting notes for Nov 17th

CHANGES, doc/ax/axcplusplus.txt, doc/changes.txt, openvdb_ax/openvdb_ax/Exceptions.h
Planning to release 9th December
https://jira.aswf.io/browse/OVDB-149
https://github.com/AcademySoftwareFoundation/openvdb-website/pull/31
=> Release 7.2.0 (OVDB-149)

openvdb/openvdb/tools/FindActiveValues.h, openvdb/openvdb/unittest/TestFindActiveValues.cc
trivial change of the copy-right statement
=> fixed copy-right

CHANGES, doc/changes.txt, openvdb/openvdb/python/CMakeLists.txt
Fixes: https://github.com/AcademySoftwareFoundation/openvdb/issues/886
=> Improve python module linkage

tsc/meetings/2021-01-05.md
=> TSC Meeting notes 2021-01-05.

tsc/meetings/2021-01-12.md
=> Added TSC minutes

CONTRIBUTING.md
=> Fixed some broken links in CONTRIBUTING.md

.github/workflows/build.yml, CHANGES, doc/changes.txt, openvdb/openvdb/tools/GridTransformer.h, openvdb/openvdb/tools/Merge.h, openvdb/openvdb/unittest/TestGridTransformer.cc, openvdb/openvdb/unittest/TestMerge.cc, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Combine.cc, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_To_Spheres.cc, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Write.cc
Bring across four bug fixes for the 7.2.2 patch release including the CSG intersection fix.
=> Prepare v7.2.2

tsc/meetings/2021-01-26.md
Adding TSC meeting notes from 2021-01-26.
=> TSC meeting notes on 2021-01-26.md.

CHANGES, doc/changes.txt, pendingchanges/fix_csg_intersection.txt, tsc/meetings/2021-02-02.md
Bonus: Merged existing pendingchanges into Changes.
=> TSC Notes for 2021-02-02

CHANGES, doc/changes.txt
=> Fixed changelogs

cmake/FindOpenVDB.cmake, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_AX.cc
=> Minor fixes to the OpenVDB AX SOP and FindOpenVDB AX CMake

openvdb/openvdb/unittest/CMakeLists.txt
This change should have been included in #978.
=> Add TestActivate unit test to the CMake

tsc/meetings/2021-03-02.md
=> TSC Meeting notes.

ci/build_windows.sh, ci/install_windows.sh
https://github.com/actions/virtual-environments/issues/2667
Failed build example: https://github.com/AcademySoftwareFoundation/openvdb/runs/2104116569
=> Updated Windows CI to install boost through vcpkg

openvdb/openvdb/tools/VolumeToMesh.h, openvdb/openvdb/unittest/TestPointMove.cc, openvdb/openvdb/unittest/TestStreamCompression.cc
Caught with assertions enabled in msvc CRT
=> Minor fixes

doc/examplecode.txt, openvdb/openvdb/Grid.cc, openvdb/openvdb/Grid.h, openvdb/openvdb/Metadata.cc, openvdb/openvdb/io/Archive.cc, openvdb/openvdb/io/Queue.cc, openvdb/openvdb/math/Maps.cc, openvdb/openvdb/openvdb.cc, openvdb/openvdb/points/AttributeArray.cc, openvdb/openvdb/points/AttributeArray.h, openvdb/openvdb/python/pyutil.h, openvdb/openvdb/tools/FastSweeping.h, openvdb/openvdb/tools/PointIndexGrid.h, openvdb/openvdb/tree/LeafBuffer.h, openvdb/openvdb/unittest/TestAttributeArray.cc, openvdb/openvdb/unittest/TestPointMove.cc, openvdb/openvdb/unittest/TestStreamCompression.cc, openvdb/openvdb/unittest/TestTools.cc, openvdb/openvdb/util/PagedArray.h, openvdb/openvdb/viewer/Viewer.cc, openvdb_ax/openvdb_ax/ast/Parse.cc, openvdb_ax/openvdb_ax/ax.cc, openvdb_houdini/openvdb_houdini/GR_PrimVDBPoints.cc, openvdb_houdini/openvdb_houdini/SOP_NodeVDB.cc, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_AX.cc, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Rasterize_Points.cc, openvdb_maya/openvdb_maya/OpenVDBPlugin.cc, pendingchanges/tbb_mutex_atomic.txt
An upstream of #969. In addition to the changes in this PR, I converted over a few tbb:mutex from AX that were added since this PR was made, removed the internal::LeafBufferFlags that is no longer relevant and added some release notes.
Thanks @BenFrantzDale for the contribution!
=> Upstream PR969: TBB Atomic/Mutex

CHANGES, doc/changes.txt
Update master with the release note changes from v7.2.3 (and a minor fix or two to the release notes).
=> Merge in v7.2.3 Changes

openvdb/openvdb/unittest/TestPointDataLeaf.cc, openvdb/openvdb/unittest/TestTree.cc
=> Additional fixes to leaks in unit tests

openvdb/openvdb/unittest/TestPointCount.cc
This could cause the test to fail if executing multiple copies of `vdb_test` on the same machine.
=> Fixed an issue which stopped TestPointCount test running concurrently

tsc/meetings/2021-02-23.md
=> Add TSC meetings notes from 02-23-2021.

CODEOWNERS, CONTRIBUTING.md, MAINTAINERS.md
=> Updated maintainers

tsc/meetings/2021-03-16.md
=> TSC Minutes March 16th

doc/ax/axfunctionlist.txt, doc/ax/gen_function_docs, doc/ax/gen_function_houdini_docs, openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc, openvdb_ax/openvdb_ax/test/integration/TestStandardFunctions.cc, openvdb_ax/openvdb_ax/test/snippets/function/adjoint, openvdb_ax/openvdb_ax/test/snippets/function/argsort, openvdb_ax/openvdb_ax/test/snippets/function/cofactor, openvdb_ax/openvdb_ax/test/snippets/function/degrees, openvdb_ax/openvdb_ax/test/snippets/function/inverse, openvdb_ax/openvdb_ax/test/snippets/function/isfinite, openvdb_ax/openvdb_ax/test/snippets/function/isinf, openvdb_ax/openvdb_ax/test/snippets/function/isnan, openvdb_ax/openvdb_ax/test/snippets/function/normalize, openvdb_ax/openvdb_ax/test/snippets/function/radians, openvdb_ax/openvdb_ax/test/snippets/function/sort, openvdb_houdini/openvdb_houdini/CMakeLists.txt, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_AX.cc, openvdb_houdini/openvdb_houdini/help/ax/functions.txt, pendingchanges/ax_functions.txt
Improvements:
- Added degree() and radians() AX helper functions for converting radians to degrees and vice versa, respectively.
- Added adjoint(), cofactor() and inverse() AX matrix functions.
- Added sort(), argsort(), isfinite(), isinf() and isnan() AX utility and math functions.
- Added Vec4 argument support to normalize() AX function.
- Removed unused int16 AX modulo function signatures.
Houdini:
- Improved the formatting and updated the OpenVDB AX SOPs help card.
- Added a help/ folder for custom help files
Additionally, I've added the scripts I use to generation the function documentation in doc/ax/
=> AX functions

openvdb/openvdb/unittest/TestPointConversion.cc
=> Fixed TestPointConversion running concurrently

CMakeLists.txt
=> Make uninstall CMake target optional.

CHANGES, doc/changes.txt, pendingchanges/abi9.txt, pendingchanges/ax_functions.txt, pendingchanges/ax_san_fixes.txt, pendingchanges/cmake_imp.txt, pendingchanges/node_visitor.txt, tsc/meetings/2021-04-13.md
=> Meeting notes for April 13th 2021

tsc/meetings/2021-04-27.md
=> Add TSC meeting notes on 04-27-2021.

pendingchanges/ax_llvm12.txt
=> Added missing pendingchanges

openvdb/openvdb/Types.h
=> [bugfix] use imath define name fix

CHANGES, doc/changes.txt
=> Minor clarifications to changes

.github/workflows/ax.yml, ci/install_macos.sh, ci/install_macos_ax.sh
=> macos TBB CI fixes

openvdb_ax/openvdb_ax/test/CMakeLists.txt, openvdb_ax/openvdb_ax/test/backend/TestStringIR.cc
=> Renamed backend/TestString.cc  to avoid overwriting integration/TestString.cc

tsc/meetings/2021-05-18.md
=> Added TSC notes

openvdb/openvdb/tools/Morphology.h, openvdb/openvdb/unittest/TestMorphology.cc
=> Improved deprecation messages on dilation and erosion API

CHANGES
Added SOP Extrapolate to the list of Changes for v8.1.0 release.
=> List addition to Extrapolate SOP to CHANGES.

tsc/meetings/2021-05-25.md
=> Add TSC Meeting Notes from 2021-05-25.

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Merge.cc
This follows the example of the VDB Combine SOP in using `GU_PrimVDB::buildFromGrid()` instead of the `hvdb::createVdbPrimitive()` wrapper and optionally passes the old primitive to copy source attributes and the old grid name to copy the name.
=> Copy primitive attributes and grid names in VDB Merge SOP for 2nd inputs

CHANGES, doc/changes.txt
=> updated change files

CMakeLists.txt, openvdb/openvdb/CMakeLists.txt, pendingchanges/dep_warnings.txt
=> Turn on warnings for upcoming deprecations

pendingchanges/README, tsc/meetings/2021-06-08.md
Added a placeholder file to avoid the pendingchanges directory
from vanishing.
Did not integerate the change notes as we have to bump our version
number first.
=> Meeting notes for June 8th 2021.

tsc/meetings/2021-06-15.md
=> Add TSC meeting notes from 2021-06-15.

openvdb/openvdb/CMakeLists.txt, openvdb/openvdb/io/TempFile.cc, pendingchanges/mingw.txt
This is a re-submission of #1102
=> Fixes for building for Windows with MinGW

tsc/meetings/2021-06-22.md
=> Add TSC meeting notes from 2021-06-22. 

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Activate.cc, pendingchanges/vdbactivate_nnoption.txt
Add an option to specify the expansion pattern.
Rename the label of the expand voxels to match the current Houdini name.
=> Add an option to specify the expansion pattern.

tsc/meetings/2021-07-13.md
Add TSC Meeting notes from 2021-07-13. Signed-off-by: Andre Pradhana <andre.pradhana@dreamworks.com>
=> Add TSC Meeting notes from 2021-07-13.

CONTRIBUTING.md, MAINTAINERS.md
=> Updated contributors

tsc/meetings/2021-07-20.md
=> Meeting notes for July 20th

.github/workflows/ax.yml, ci/build.sh, openvdb/openvdb/tools/Count.h, openvdb/openvdb/tree/NodeManager.h, openvdb/openvdb/tree/Tree.h, openvdb/openvdb/unittest/TestCount.cc, pendingchanges/count_tools.txt
Adding:
* tools::countActiveLeafVoxels() [+bbox version]
* tools::countInactiveVoxels()
* tools::countInactiveLeafVoxels()
* tools::countActiveTiles()
and changed the Tree methods to use these tools.
=> Counting Tools

.github/workflows/houdini.yml, .github/workflows/houdini_cache_update.yml
=> Fixed an issue where the Houdini Cache wasn't being saved correctly

tsc/meetings/2021-08-03.md
=> Add TSC meeting notes from 2021-08-03.

openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc, openvdb_ax/openvdb_ax/test/integration/TestHarness.cc, openvdb_ax/openvdb_ax/test/integration/TestStandardFunctions.cc, openvdb_ax/openvdb_ax/test/snippets/function/hsvtorgb, openvdb_ax/openvdb_ax/test/snippets/function/rgbtohsv, pendingchanges/ax_hsvrgb.txt
=> Introduced hsvtorgb and rgbtohsv functions to AX

openvdb/openvdb/math/Math.h, pendingchanges/size_t_abs.txt
=> Minor update from PR1097 and added pendingchanges

CHANGES, doc/changes.txt, pendingchanges/ax_hsvrgb.txt, pendingchanges/count_tools.txt, pendingchanges/houdini_dso_names.txt, pendingchanges/mingw.txt, pendingchanges/nodemanagergrainsize.txt, pendingchanges/point_conversion_vec3f.txt, pendingchanges/size_t_abs.txt, pendingchanges/vdbactivate_nnoption.txt, pendingchanges/vdblod_metadata.txt, tsc/meetings/2021-09-14.md
Also, integrate the pending changes.
=> Meeting notes Sept 14

pendingchanges/pythoninstall.txt
=> Added pendingchanges

CHANGES, doc/changes.txt, pendingchanges/ax.txt, pendingchanges/explicit_instantiation.txt
=> Modify release notes.

CHANGES, doc/changes.txt, pendingchanges/ax.txt, pendingchanges/explicit_instantiation.txt
=> Merge v9.0.0_rc to master

tsc/meetings/2021-08-31.md, tsc/meetings/2021-10-26.md
Add TSC meeting notes from 10/26/2021 and 08/31/2021.
=> Add TSC meeting notes.

tsc/meetings/2021-11-02.md
=> Meeting notes for Nov 2nd.

CHANGES, openvdb/openvdb/tools/LevelSetSphere.h
=> Fixed a range bug in LevelSetSphere

openvdb/openvdb/python/test/TestOpenVDB.py
Fixes https://github.com/AcademySoftwareFoundation/openvdb/issues/698
Implements https://github.com/AcademySoftwareFoundation/openvdb/pull/986
=> Minor fix to python test calling removed time.clock()

CHANGES, openvdb/openvdb/Types.h, pendingchanges/combine_extended.txt
Fixes https://github.com/AcademySoftwareFoundation/openvdb/issues/1127
=> Fixed a bug in Tree::combineExtended

.github/workflows/docs.yml
=> Changed the docs workflow to deploy to the website repo

.github/workflows/houdini.yml, .github/workflows/weekly.yml
The v4 accidentally got uploaded without the timestamp.
=> Bump cache version to v5

CHANGES, doc/changes.txt
Update doc/changes.txt and CHANGES.
=> Update doc/changes.txt and CHANGES.

CHANGES, doc/changes.txt
Change release date of Version 8.2.0 to November 24.
=> Change release date of Version 8.2.0 to November 24.

CHANGES, doc/changes.txt
I incorporated the list of changes from v8.2.0 release to CHANGES and doc/changes. Do you think it is safe to deploy a new website from master branch once it's merged in? I foresee a problem that the new documentation will display OpenVDB 9.0.1, instead of OpenVDB 9.0.0.
=> Update CHANGES and doc/changes.txt to include v8.2.0 release.

openvdb/openvdb/points/PointStatistics.h
=> Minor fix to point statistics loop access

.github/workflows/build.yml, .github/workflows/houdini.yml, .github/workflows/weekly.yml
=> Use gtest from ASWF images

openvdb/openvdb/python/CMakeLists.txt, pendingchanges/cmake_python.txt
=> Fixed an issue with find_python and CMake 3.18

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Diagnostics.cc
Makes the toggles consistent with our usual layout.
=> Change the TOGGLE to be consistent with our usual way

openvdb/openvdb/python/pyGrid.h, openvdb/openvdb/tools/Count.h, openvdb/openvdb/viewer/RenderModules.cc, pendingchanges/minmax.txt
=> Added pendingchanges for minmax

tsc/meetings/2022-01-18.md
Meeting notes for January 18th.
=> Meeting notes for January 18th.

CHANGES, doc/changes.txt
This is to merge v8.2.0_rc back to v8.2.
=> Merge v8.2.0 rc to v8.2

tsc/meetings/2022-02-08.md, tsc/meetings/2022-02-22.md
=> Add TSC meeting notes from 2022-02-08 and 2022-02-22.

openvdb/openvdb/points/PointConversion.h, openvdb_ax/openvdb_ax/CMakeLists.txt, openvdb_ax/openvdb_ax/codegen/Codecs.cc, openvdb_ax/openvdb_ax/codegen/Codecs.h, openvdb_ax/openvdb_ax/codegen/FunctionRegistry.h, openvdb_ax/openvdb_ax/codegen/FunctionTypes.cc, openvdb_ax/openvdb_ax/codegen/FunctionTypes.h, openvdb_ax/openvdb_ax/codegen/PointComputeGenerator.cc, openvdb_ax/openvdb_ax/codegen/PointComputeGenerator.h, openvdb_ax/openvdb_ax/codegen/PointFunctions.cc, openvdb_ax/openvdb_ax/codegen/Types.h, openvdb_ax/openvdb_ax/codegen/Utils.h, openvdb_ax/openvdb_ax/compiler/Compiler.cc, openvdb_ax/openvdb_ax/compiler/PointExecutable.cc, openvdb_ax/openvdb_ax/compiler/PointExecutable.h, openvdb_ax/openvdb_ax/test/CMakeLists.txt, openvdb_ax/openvdb_ax/test/backend/TestCodecs.cc, openvdb_ax/openvdb_ax/test/compiler/TestPointExecutable.cc, openvdb_ax/openvdb_ax/test/snippets/keyword/whileLoopKeywords, pendingchanges/ax_codecs.txt
Improvements:
- Significant performance improvements to AX point kernels, primarily due to
providing AX access to attribute buffers for superior code generation.
=> OpenVDB AX Point Kernel Improvements

CHANGES, doc/changes.txt, pendingchanges/ax_bin.txt, pendingchanges/ax_bindings.txt, pendingchanges/ax_windows.txt, pendingchanges/cmake_python.txt, pendingchanges/combine_extended.txt, pendingchanges/minmax.txt, pendingchanges/unittest_streampos.txt, pendingchanges/vdbmerge_fix.txt, tsc/meetings/2022-03-22.md
Consolidate the pending changes.
=> Add meeting notes for March 22nd.

openvdb/openvdb/TypeList.h, openvdb/openvdb/openvdb.cc, openvdb/openvdb/openvdb.h, openvdb/openvdb/points/points.cc, openvdb/openvdb/unittest/TestTypes.cc, pendingchanges/type_lists.txt
Due to interest in the last TSC, I've split this out into a more complete and isolated PR. Thoughts welcome
=> Exposed TypeLists of the default set of OpenVDB types

tsc/meetings/2022-02-02.md, tsc/meetings/2022-03-01.md, tsc/meetings/2022-03-29.md
Added some meeting notes from February and March.
Signed-off-by: Rich Jones <richhones@users.noreply.github.com>
=> Added meeting notes

tsc/meetings/2022-04-05.md
=> Add TSC Meeting notes from 04-05-2022.

tsc/meetings/2022-04-26.md
=> Add TSC Meeting Notes April 26, 2022.

cmake/FindTBB.cmake, openvdb/openvdb/Platform.h, pendingchanges/findtbb.txt
- FindTBB.cmake now prioritises newer TBB installations and warns if multiple are found
- Silenced unecessary pragmas from deprecation macros
Addresses: https://github.com/AcademySoftwareFoundation/openvdb/pull/1349
=> Various Improvements

CMakeLists.txt, ci/install_llvm_windows.sh, openvdb_ax/openvdb_ax/codegen/PointComputeGenerator.cc, openvdb_ax/openvdb_ax/compiler/PointExecutable.cc, openvdb_ax/openvdb_ax/test/CMakeLists.txt
- Fixed AX weekly CI (no idea why the CMake stopped working)
- Fixed an issue where the AX cmd tests wern't being run since the binary relocation
- Fixed an issue on Windows/MSVC with UL being 32bits
=> Various AX Improvements/Fixes

openvdb/openvdb/tools/VolumeToMesh.h
=> Improve adaptivity docs on volumeToMesh function

nanovdb/nanovdb/NanoVDB.h, nanovdb/nanovdb/util/GridBuilder.h, nanovdb/nanovdb/util/GridChecksum.h, nanovdb/nanovdb/util/IO.h, nanovdb/nanovdb/util/OpenToNanoVDB.h, nanovdb/nanovdb/util/Primitives.h
minor changes that sync up NanoVDB, mostly related to warnings
=> minor changes that sync up NanoVDB, mostly related to warnings

.github/workflows/weekly.yml
skip internal namespace symbols but include everything else
=> Improved ABI check

CHANGES, doc/changes.txt
Fixing the date on the release notes. Should be good to complete the release today.
=> Update release date for v9.1.0

openvdb_houdini/openvdb_houdini/GEO_PrimVDB.cc, openvdb_houdini/openvdb_houdini/GEO_PrimVDB.h, openvdb_houdini/openvdb_houdini/GU_PrimVDB.h
Synchronizing these files with the future 19.5 versions.
=> Synchronize with future 19.5 version.

tsc/meetings/2022-06-14.md
=> TSC Meeting notes June 14th.

.github/workflows/build.yml
=> Disabled windows static debug CI build

openvdb/openvdb/python/pyGrid.h, pendingchanges/math.txt, pendingchanges/volume2mesh_perf.txt
Related to: https://github.com/AcademySoftwareFoundation/openvdb/pull/1421#issuecomment-1169773997
=> Python module VolumeToMesh compile fix

.github/workflows/docs.yml, .github/workflows/weekly.yml, cmake/config/OpenVDBCXX.cmake, doc/doc.txt, tsc/process/release.md
This is a copy of https://github.com/AcademySoftwareFoundation/openvdb/pull/1071 - tested and we can now update the website with one click! This is ready to be merged
=> Added code coverage with website deployment

.github/workflows/ax.yml, .github/workflows/build.yml, .github/workflows/weekly.yml, CHANGES, ci/build.sh, ci/install_macos_ax.sh, ci/install_windows.sh, cmake/FindTBB.cmake, doc/ax/ax.txt, openvdb/openvdb/python/CMakeLists.txt, openvdb/openvdb/python/test/TestOpenVDB.py, openvdb/openvdb/unittest/TestAttributeArrayString.cc, openvdb/openvdb/unittest/TestCoord.cc, openvdb_ax/openvdb_ax/CMakeLists.txt, openvdb_ax/openvdb_ax/codegen/Codecs.h, openvdb_ax/openvdb_ax/compiler/PointExecutable.h, openvdb_ax/openvdb_ax/compiler/VolumeExecutable.cc, openvdb_ax/openvdb_ax/compiler/VolumeExecutable.h, openvdb_cmd/vdb_print/main.cc, pendingchanges/ax_build.txt
Incorporatres some changes from #1445 but in summary:
- Fixes #1447, where AX symbols were not being exported
- Added python tests for AX
- Fixed some CMake issues with TBB and Boost
- CI and doc updates
=> Various build fixes

.github/workflows/weekly.yml, openvdb_ax/openvdb_ax/CMakeLists.txt, openvdb_ax/openvdb_ax/codegen/Codecs.cc, openvdb_ax/openvdb_ax/codegen/ComputeGenerator.cc, openvdb_ax/openvdb_ax/codegen/ComputeGenerator.h, openvdb_ax/openvdb_ax/codegen/FunctionTypes.cc, openvdb_ax/openvdb_ax/codegen/FunctionTypes.h, openvdb_ax/openvdb_ax/codegen/PointComputeGenerator.cc, openvdb_ax/openvdb_ax/codegen/StandardFunctions.cc, openvdb_ax/openvdb_ax/codegen/StringFunctions.cc, openvdb_ax/openvdb_ax/codegen/Utils.h, openvdb_ax/openvdb_ax/codegen/VolumeComputeGenerator.cc, openvdb_ax/openvdb_ax/codegen/VolumeFunctions.cc, openvdb_ax/openvdb_ax/compiler/Compiler.cc, openvdb_ax/openvdb_ax/test/backend/TestFunctionTypes.cc, pendingchanges/ax_build.txt, pendingchanges/llvm_deprecations.txt
=> Fixed llvm deprecation warnings in AX

tsc/meetings/2022-08-16.md
=> Meeting notes for August 16th.

cmake/config/OpenVDBCXX.cmake, pendingchanges/msvc_conformance.txt
=> Add MSVC compiler options to improve C++ conformance

openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Activate.cc, pendingchanges/activate_convex.txt
Unfortunately this requires GU_ConvexHull3D changes from future
houdini, so has version guards to restrict use.
Code for faster sdf-activation using dynamic node manager.
=> Code to do convex-hull based activation.

tsc/meetings/2022-09-27.md
=> TSC notes for September 27th.

openvdb/openvdb/math/Tuple.h, pendingchanges/tuple.txt
Fixed a bug in math/Tuple.h that prevented compilation with VS2017
=> Fix to tuple

tsc/meetings/2022-07-26.md
Signed-off-by: Andre Pradhana <andre.pradhana@gmail.com>
=> Add TSC Meeting Notes on 2022-07-26.

doc/nanovdb/SourceTree.md, nanovdb/nanovdb/Readme.md
Fixed broken links in nanovdb/Readme.md
=> fixed links in nanovdb/Readme.md

nanovdb/nanovdb/NanoVDB.h, nanovdb/nanovdb/PNanoVDB.h, nanovdb/nanovdb/unittest/TestNanoVDB.cc, nanovdb/nanovdb/util/IndexGridBuilder.h
=> reduced index of IndexGrid by 4

doc/examplecode.txt, openvdb/openvdb/openvdb.cc, openvdb/openvdb/openvdb.h, openvdb/openvdb/unittest/TestInit.cc, openvdb_ax/openvdb_ax/test/compiler/TestVolumeExecutable.cc, pendingchanges/remove_string_grids.txt
This was deprecated in VDB 9.0.
=> Remove string grids

tsc/meetings/2022-05-31.md, tsc/meetings/2022-07-19.md, tsc/meetings/2022-09-20.md, tsc/meetings/2022-10-11.md
Signed-off-by: Richard Jones <richardj@ilm.com>
=> Adding meeting notes

nanovdb/nanovdb/util/CudaDeviceBuffer.h
minor fixes to address compiler warnings
=> fixed compile warning on Windows

doc/changes.txt
Adding a paragraph in the documentation.
Signed-off-by: Andre Pradhana <andre.pradhana@gmail.com>
=> Minor fix in the documentation. 

doc/changes.txt
Signed-off-by: Andre Pradhana <andre.pradhana@gmail.com>
=> Add vdb_tool in a block announcement.

openvdb_cmd/vdb_tool/CMakeLists.txt
Add install command to vdb_tool in CMakeLists.
=> Add install in CMakeLists for vdb_tool.

tsc/meetings/2022-22-01.md
=> Meeting notes for Nov 1st, 2022

CHANGES, doc/changes.txt, pendingchanges/findopenvdb_cxx17.txt, pendingchanges/fixseampoint.txt
=> Updated change logs for 10.0.1

CMakeLists.txt, cmake/config/OpenVDBVersions.cmake
=> Switched to automatically generating CMake ABI options

tsc/meetings/2022-11-01.md, tsc/meetings/2022-11-29.md
(Also renamed one of the older meeting notes that had the wrong filename)
=> Meeting notes 29th Nov

.github/workflows/ax.yml, .github/workflows/build.yml, .github/workflows/houdini.yml, .github/workflows/nanovdb.yml, .github/workflows/weekly.yml, ci/build.sh
=> Fixed forked repo action runners

openvdb/openvdb/unittest/TestAttributeArrayString.cc
=> Minor C++20 build fix

tsc/meetings/2023-01-10.md
Signed-off-by: Andre Pradhana <andre.pradhana@gmail.com>
=> Add TSC Meeting Notes 2023-01-10.md.

tsc/meetings/2023-01-17.md
=> TSC Notes for Jan 17 2023

openvdb/openvdb/Platform.h, openvdb/openvdb/TypeList.h, openvdb/openvdb/Types.h, openvdb/openvdb/tree/ValueAccessor.h, openvdb/openvdb/unittest/CMakeLists.txt, openvdb/openvdb/unittest/TestTypeList.cc, openvdb/openvdb/unittest/TestTypes.cc, openvdb/openvdb/unittest/TestValueAccessor.cc, openvdb_ax/openvdb_ax/codegen/VolumeFunctions.cc, openvdb_ax/openvdb_ax/test/compiler/TestVolumeExecutable.cc, pendingchanges/value_accessor.txt
=> Consolidated ValueAccessor implementations

openvdb/openvdb/Grid.cc, openvdb/openvdb/io/Compression.cc, openvdb/openvdb/io/GridDescriptor.cc, openvdb/openvdb/math/FiniteDifference.h, openvdb/openvdb/unittest/TestUtil.cc, openvdb/openvdb/util/Name.h, openvdb_cmd/vdb_lod/main.cc, openvdb_cmd/vdb_render/main.cc, openvdb_cmd/vdb_view/Viewer.cc, openvdb_cmd/vdb_view/Viewer.h, openvdb_cmd/vdb_view/main.cc
=> Removed boost/string methods in favour of utility methods in util/Name.h

openvdb_ax/openvdb_ax/CMakeLists.txt, openvdb_ax/openvdb_ax/codegen/Codecs.cc, openvdb_ax/openvdb_ax/test/backend/TestCodecs.cc, openvdb_ax/openvdb_ax/test/compiler/TestPointExecutable.cc, openvdb_ax/openvdb_ax/util/x86.cc, openvdb_ax/openvdb_ax/util/x86.h, pendingchanges/ax_f16c.txt
=> Fixed a crash in AX when target does not have f16c support

openvdb/openvdb/tree/LeafManager.h, openvdb/openvdb/tree/Tree.h, openvdb/openvdb/unittest/TestLeafManager.cc, pendingchanges/leafmanager_root_fix.txt
=> LeafManager LeafArray bugfix from RootNode<LeafNode>

tsc/meetings/2023-04-18.md
Add TSC Meeting Notes from April 18, 2023.
=> Add TSC Meeting Notes April 18, 2023.

openvdb_houdini/openvdb_houdini/GEO_PrimVDB.cc, openvdb_houdini/openvdb_houdini/GEO_PrimVDB.h, openvdb_houdini/openvdb_houdini/GU_PrimVDB.cc, openvdb_houdini/openvdb_houdini/SOP_OpenVDB_Activate.cc
Change to PRM_UI rather than PRM_FREE to match H20 version of parms in activate.
=> Synchronize the GEO reference implementations with upcoming H20.

openvdb/openvdb/tree/LeafNodeBool.h, openvdb/openvdb/unittest/TestLeafBool.cc, pendingchanges/leafnodebool.txt
=> Fixed a bug with LeafNodeBool TopologyCopy constructor

tsc/meetings/2023-09-19.md
=> Notes for TSC meeting.

.github/workflows/ax.yml, .github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/houdini.yml, .github/workflows/weekly.yml, ci/build.sh, cmake/FindOpenVDB.cmake, nanovdb/nanovdb/CMakeLists.txt, openvdb/openvdb/CMakeLists.txt, openvdb/openvdb/Platform.h, openvdb/openvdb/python/CMakeLists.txt, openvdb/openvdb/tools/MultiResGrid.h, openvdb/openvdb/tools/ValueTransformer.h, openvdb/openvdb/util/PagedArray.h, openvdb_ax/openvdb_ax/CMakeLists.txt, pendingchanges/cplusplus20.txt
Closes https://github.com/AcademySoftwareFoundation/openvdb/issues/1623
=> Minor CMake Fixes/C++20 support

nanovdb/nanovdb/NanoVDB.h, nanovdb/nanovdb/examples/ex_voxels_to_grid_cuda/ex_voxels_to_grid_cuda.cu, nanovdb/nanovdb/util/GridHandle.h, nanovdb/nanovdb/util/cuda/CudaPointsToGrid.cuh
Fixed a bug related to the new fileformat
=> bug-fix to nanovdb related to new I/O

openvdb/openvdb/tools/Activate.h, pendingchanges/ubsan.txt
This should finally completely fix the UBSAN builds
=> Fixed an instance of undefined behaviour in tools::activate

tsc/meetings/2023-11-07.md
Add TSC meeting notes from 2023-11-07.
=> Add TSC meeting notes from 2023-11-07.

CMakeLists.txt, pendingchanges/explicit_inst_win.txt
https://github.com/AcademySoftwareFoundation/openvdb/issues/1718
https://github.com/AcademySoftwareFoundation/openvdb/issues/1624
=> Turn off USE_EXPLICIT_INSTANTIATION on Windows by default

tsc/meetings/2024-01-16.md
TSC Meeting with Autodesk on Jan 16, 2024.
=> Add TSC notes from 2024-01-16.

.github/workflows/houdini.yml, .github/workflows/weekly.yml, ci/download_houdini.py, ci/download_houdini.sh
Requires the weekly CI to run to populate the new MacOS cache. Example successful run here: 
https://github.com/Idclip/openvdb/actions/runs/7593582824/job/20684195380
=> Introduced CI for Houdini on MacOS

RE-LICENSE_NOTE.txt, README.md
Added file to indicate that OpenVDB is changing license from Mozilla v2 to Apache v2.
=> added RE-LICENSE_NOTE.txt

RE-LICENSE_NOTE.txt
=> MPL to Apache relicense

RE-LICENSE_NOTE.txt
Our approval is marked by the addition of our name to the RE-LICENSE_NOTE.txt.
=> Digital Domain 3.0, Inc. approved relicense from MPL-2.0 to Apache-2.0

RE-LICENSE_NOTE.txt
Signed-off-by: Brian Sharpe <brisharpe@yahoo.com>
=> Adding "Brian Sharpe" to the RE-LICENCE node

tsc/meetings/2023-01-24.md, tsc/meetings/2023-05-02.md, tsc/meetings/2023-09-05.md, tsc/meetings/2023-10-17.md, tsc/meetings/2024-02-06.md, tsc/meetings/2024-04-06.md, tsc/meetings/2024-04-23.md
Adds meeting notes from 
2023-01-24
2023-05-02
2023-09-05
2023-10-17
2024-02-06
2024-04-06
2024-04-23
=> Various TSC meeting notes

openvdb/openvdb/unittest/TestLinearInterp.cc
fixed precision issue in unit-test on OSX M3
=> fixed precision issue in unit-test on OSX M3

fvdb/README.md, fvdb/ci/Dockerfile.runner, fvdb/docs/tutorials/basic_concepts.md, fvdb/fvdb/nn/modules.py, fvdb/setup.py, fvdb/src/GridBatch.cpp, fvdb/src/GridBatch.h, fvdb/src/JaggedTensor.cpp, fvdb/src/detail/GridBatchImpl.cu, fvdb/src/detail/TorchDeviceBuffer.cpp, fvdb/src/detail/io/SaveNanoVDB.cpp, fvdb/src/detail/ops/JCat0.cu, fvdb/src/detail/ops/JIdxForJOffsets.cu, fvdb/src/detail/ops/JOffsetsFromJIdx.cu, fvdb/src/detail/ops/JaggedTensorIndex.cu, fvdb/src/detail/ops/Ops.h, fvdb/src/detail/ops/VolumeRender.cu, fvdb/src/detail/utils/Utils.h, fvdb/src/python/GridBatchBinding.cpp, fvdb/tests/unit/test_jagged_tensor.py
Also includes small updates to basic_concepts docs and README
=> fVDB Updates: Bugs fixed for multi-GPU support, JaggedTensor slicing/indexing CUDA kernels

.github/workflows/weekly.yml, openvdb_ax/openvdb_ax/ast/AST.h, openvdb_ax/openvdb_ax/codegen/Codecs.h, openvdb_ax/openvdb_ax/codegen/FunctionTypes.cc, openvdb_ax/openvdb_ax/compiler/Compiler.cc, openvdb_ax/openvdb_ax/compiler/PointExecutable.cc
There was an unused variable warning that was failing the CI.
=> Fix ubsan weekly CI check

tsc/meetings/2024-11-05.md
Meeting notes from 2024-11-05.
=> 2024-11-05 Meeting Notes

openvdb_cmd/vdb_view/RenderModules.cc
=> Specifically include glu.h on windows

nanovdb/nanovdb/tools/cuda/IndexToGrid.cuh, nanovdb/nanovdb/unittest/TestNanoVDB.cu, pendingchanges/nanovdb.txt
This is a minor rewrite of PR #2013  (with more documentation)
=> fixed offset bug in IndexToGrid - see PR2013

openvdb/openvdb/Types.h, openvdb/openvdb/math/Mat.h, openvdb/openvdb/math/Mat3.h, openvdb/openvdb/points/AttributeArray.h, openvdb/openvdb/points/PointRasterizeSDF.h, openvdb/openvdb/points/PointTransfer.h, openvdb/openvdb/points/PrincipalComponentAnalysis.h, openvdb/openvdb/points/impl/PointRasterizeEllipsoidsSDFImpl.h, openvdb/openvdb/points/impl/PointRasterizeSDFImpl.h, openvdb/openvdb/points/impl/PointRasterizeTrilinearImpl.h, openvdb/openvdb/points/impl/PrincipalComponentAnalysisImpl.h, openvdb/openvdb/unittest/CMakeLists.txt, openvdb/openvdb/unittest/TestPCA.cc, openvdb/openvdb/unittest/TestPointRasterizeSDF.cc, openvdb/openvdb/unittest/TestPointRasterizeTrilinear.cc, pendingchanges/surfacing.txt
Re-created from https://github.com/AcademySoftwareFoundation/openvdb/pull/1634 with additional improvements
```
OpenVDB:
New:
- Introduced anisotropic surfacing tools in points/PointRasterizeSDF.h
and principle component analysis (PCA) methods in points/PrincipleComponentAnalysis.h.
The latter tool analyses point neighborhoods and computes affine
transformations representing elliptical distributions. The prior tool
takes rotational and stretch point attributes (optionally computed from
the prior PCA methods) and generates anisotropic surfaces.
- Added OPENVDB_HAS_INVOKABLE_MEMBER_FUNCTION and OPENVDB_HAS_MEMBER_FUNCTION
macros to help determine the presence and compatibility of interface
member functions at compile time.
API Changes:
- Re-worked the API in PointRasterizeSDF.h with the …
```
=>  Introduced Anisotropic Surfacing Kernels and PCA methods

ci/download_houdini.sh
=> Fixed Houdini download scripts with new container images
